#!/usr/bin/env python3
"""gt_digest.py -- a cheap first read of an append-only research.md.

    gt_digest.py write --vault V --project SLUG [--dry-run] [--json]
    gt_digest.py check --vault V --project SLUG [--json]

`research.md` is append-only and grows without bound; gt-open falls back to reading only its
headings past ~200 lines, and a heading alone loses the substance. `research-digest.md` sits
beside it and is REWRITTEN on every /gt:gt-work:

  * Pinned findings -- up to 5 sections whose `## ` heading carries `[pinned]`, newest first,
    whatever their age;
  * Latest sections -- the last 20 `## ` sections, newest first, one line each.

Each line is the section's heading and its first non-blank, non-heading body line, cut to 120
characters. DETERMINISTIC: no model summarises anything, so the digest says only what the file
already says. research.md is never modified.

`write` goes through the write queue and drains it (Core rule 1, queue-first): the digest as a
`replace-file` (an absent file is created), and -- the first time -- a line in the project's
`memory/MEMORY.md` index pointing at it (an `append`, or a `create` when there is no index).
The digest's frontmatter records `research_sha256`, the hash of the research.md it was built
from. `check` exits 0 only when the digest exists and that hash matches research.md as it is
now -- that is what gt-open asks before reading the digest instead of the headings.

Exit (write): 0 written or unchanged | 1 queued but not applied (held / escalated: the message
says which) | 2 usage | 3 no research.md.  (check): 0 current | 1 missing or stale | 2 usage.
"""
import argparse
import datetime
import hashlib
import json
import os
import re
import sys
from pathlib import Path

HERE = os.path.dirname(os.path.abspath(__file__))
LATEST = 20
PINNED = 5
WIDTH = 120
PIN = re.compile(r"\[pinned\]", re.I)
DIGEST = "research-digest.md"
INDEX_LINE = ("- [Research digest](../research-digest.md) — generated one-line summaries of "
              "research.md, newest first, plus pinned findings (gt_digest.py; rewritten by "
              "/gt:gt-work)")


def _read(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except (OSError, UnicodeDecodeError):
        return None


def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sections(text):
    """-> [(heading, first body line)] in file order, for every `## ` section."""
    out, head, first = [], None, None
    fence = False
    for line in text.split("\n"):
        if re.match(r"^\s*(```|~~~)", line):
            fence = not fence
        if not fence and line.startswith("## "):
            if head is not None:
                out.append((head, first or ""))
            head, first = line[3:].strip(), None
            continue
        if head is not None and first is None and not fence:
            s = line.strip()
            if s and not s.startswith("#") and not re.fullmatch(r"[-*_]{3,}", s):
                first = re.sub(r"^([-*>]|\d+\.)\s+", "", s)
    if head is not None:
        out.append((head, first or ""))
    return out


def _cut(text, n=WIDTH):
    text = text.replace("|", "\\|")
    return text if len(text) <= n else text[:n - 1].rstrip() + "…"


def render(slug, research):
    secs = sections(research)
    newest = list(reversed(secs))
    pinned = [s for s in newest if PIN.search(s[0])][:PINNED]
    latest = newest[:LATEST]
    L = ["---", "type: research-digest", "project: %s" % slug,
         "generated: %s" % datetime.datetime.now().astimezone().isoformat(timespec="seconds"),
         "research_sha256: %s" % sha(research), "sections: %d" % len(secs), "---", "",
         "# Research digest — %s" % slug, "",
         "Generated by `gt_digest.py` from `research.md`, which stays the append-only record. "
         "Rewritten on every /gt:gt-work; do not edit by hand. One line per section: its "
         "heading and its first line, nothing inferred.", "",
         "## Pinned findings", ""]
    L += ["- **%s** — %s" % (_cut(h, 200), _cut(b)) for h, b in pinned] or ["_none pinned_"]
    L += ["", "## Latest sections (newest first, %d of %d)" % (len(latest), len(secs)), ""]
    L += ["- **%s** — %s" % (_cut(h, 200), _cut(b)) for h, b in latest] or ["_no sections_"]
    return "\n".join(L) + "\n"


def _body(text):
    """The digest without its `generated:` line, to tell a real change from a re-run."""
    return re.sub(r"^generated: .*$", "", text or "", count=1, flags=re.M)


def _spool():
    """The vault tools' gt_spool, shipped beside this script under templates/tools: the ONE
    slug -> Projects/<path> resolver (0.18.0), shared with gt_adr and vault_init."""
    tools = os.path.join(os.path.dirname(HERE), "templates", "tools")
    if tools not in sys.path:
        sys.path.insert(0, tools)
    import gt_spool
    return gt_spool


def check(vault, slug):
    base = os.path.join(vault, "Projects", slug)
    research = _read(os.path.join(base, "research.md"))
    digest = _read(os.path.join(base, DIGEST))
    if research is None:
        return False, "no research.md"
    if digest is None:
        return False, "no %s" % DIGEST
    m = re.search(r"^research_sha256:\s*([0-9a-f]{64})\s*$", digest, re.M)
    if not m or m.group(1) != sha(research):
        return False, "%s is older than research.md" % DIGEST
    return True, "current"


def write(vault, slug, dry_run):
    base = os.path.join(vault, "Projects", slug)
    research = _read(os.path.join(base, "research.md"))
    if research is None:
        return 3, "no research.md at Projects/%s" % slug, []
    text = render(slug, research)
    rel = "Projects/%s/%s" % (slug, DIGEST)
    writes = []
    if _body(_read(os.path.join(base, DIGEST))) != _body(text):
        writes.append({"path": rel, "op": "replace-file", "content": text,
                       "hint": "gt_digest: regenerate the research digest"})
    idx_rel = "Projects/%s/memory/MEMORY.md" % slug
    idx = _read(os.path.join(vault, idx_rel))
    if idx is None:
        writes.append({"path": idx_rel, "op": "create",
                       "content": "# Memory Index\n\n<!-- One entry per file: - [Title](file.md) "
                                  "— description -->\n\n" + INDEX_LINE + "\n",
                       "hint": "gt_digest: index the research digest"})
    elif DIGEST not in idx:
        writes.append({"path": idx_rel, "op": "append", "content": INDEX_LINE + "\n",
                       "hint": "gt_digest: index the research digest"})
    if not writes:
        return 0, "unchanged", []
    if dry_run:
        return 0, "dry-run: would queue %s" % ", ".join("%s %s" % (w["op"], w["path"])
                                                       for w in writes), writes
    sys.path.insert(0, HERE)
    import gt_write_queue as wq                                   # noqa: PLC0415
    try:
        results, note = wq.submit(Path(vault), writes)
    except OSError as exc:
        return 1, "could not queue: %s" % exc, writes
    bad = [r for r in results if r["decision"] not in ("apply", "deduplicate")]
    if bad:
        return 1, "; ".join("%s %s: %s%s" % (r["op"], r["path"], r["decision"],
                                             (" (%s)" % r.get("reason")) if r.get("reason") else "")
                            for r in bad) + ("; " + note if note else ""), writes
    return 0, "wrote %s" % ", ".join(w["path"] for w in writes), writes


def main(argv=None):
    ap = argparse.ArgumentParser(description="the research digest beside research.md")
    sub = ap.add_subparsers(dest="cmd", required=True)
    for name in ("write", "check"):
        p = sub.add_parser(name)
        p.add_argument("--vault", required=True, help="the vault (never inferred)")
        p.add_argument("--project", required=True, help="project slug")
        p.add_argument("--json", action="store_true")
        if name == "write":
            p.add_argument("--dry-run", action="store_true", help="say what would be queued")
    a = ap.parse_args(argv)
    if ".." in a.project.split("/") or a.project in (".",) or os.path.isabs(a.project) \
            or "\\" in a.project:
        print("--project takes a slug, not a path: %r" % a.project, file=sys.stderr)
        return 2
    vault = os.path.abspath(os.path.expanduser(a.vault))
    # The shared resolver (0.18.0): a bare sub-project slug writes beside
    # Projects/<parent>/<slug>/research.md, never a stray top-level folder.
    S = _spool()
    try:
        a.project = S.resolve_project(vault, a.project,
            allow_unregistered=True)  # an existing folder, as before; never creates
    except S.ProjectNotFound as exc:
        print("gt_digest: %s" % exc, file=sys.stderr)
        return 3
    if a.cmd == "check":
        ok, why = check(vault, a.project)
        print(json.dumps({"current": ok, "why": why}) if a.json else
              "%s: %s" % ("current" if ok else "stale", why))
        return 0 if ok else 1
    rc, msg, writes = write(vault, a.project, a.dry_run)
    if a.json:
        print(json.dumps({"rc": rc, "message": msg,
                          "writes": [{"path": w["path"], "op": w["op"]} for w in writes]}))
    else:
        print("gt_digest: %s" % msg, file=sys.stderr if rc else sys.stdout)
    return rc


if __name__ == "__main__":
    sys.exit(main())
