#!/usr/bin/env python3
"""Every vault file gt has ever shipped, by content: templates/shipped-hashes.json.

install.sh refreshes two kinds of file INSIDE a vault -- the vault tools
(Projects/golden-thread/tools/*.py) and the attribution git hooks (.githooks/*). A
refresh may replace a vault copy only when that copy is byte-identical to something gt
itself shipped; anything else is the owner's edit and is kept (tools) or backed up
first (hooks). Until 0.15.0 the tool refresh compared MODIFICATION TIMES instead, so an
owner edit older on disk than a freshly copied release was called "stale" and replaced,
and a pristine copy newer than the release was called "ahead".

The hash list is generated from git -- every blob ever committed under
*/templates/tools/ or */templates/githooks/ -- plus the version directories in the
working tree (a release being built is not committed yet). A blob from a commit between
releases never reached a user, but a vault copy equal to one is still gt's text, not the
owner's, so listing it can only prevent a false "modified locally".

  dev/shipped_hashes.py <release-dir>           write <release-dir>/templates/shipped-hashes.json
  dev/shipped_hashes.py <release-dir> --check   exit 1 if the file is missing or stale
"""
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

KINDS = ("tools", "githooks")
PATH_RE = re.compile(r"/templates/(tools|githooks)/([^/]+)$")


def from_git(repo):
    """-> {kind: {name: set(sha256)}} for every committed blob under the template dirs."""
    out = {k: {} for k in KINDS}
    try:
        raw = subprocess.run(["git", "-C", str(repo), "log", "--all", "--raw", "--no-abbrev",
                              "--format="], capture_output=True, text=True, check=True).stdout
    except (OSError, subprocess.CalledProcessError):
        return out
    blobs = {}
    for line in raw.splitlines():
        # :100644 100644 <old> <new> M\tpath   (a rename line carries two paths)
        if not line.startswith(":") or "\t" not in line:
            continue
        meta, paths = line.split("\t", 1)
        new = meta.split()[3]
        m = PATH_RE.search(paths.split("\t")[-1])
        if m and set(new) != {"0"}:
            blobs[new] = (m.group(1), m.group(2))
    if not blobs:
        return out
    p = subprocess.run(["git", "-C", str(repo), "cat-file", "--batch"],
                       input="".join(b + "\n" for b in blobs).encode(),
                       capture_output=True, check=True)
    data, pos = p.stdout, 0
    for b in blobs:
        header_end = data.index(b"\n", pos)
        size = int(data[pos:header_end].split()[2])
        body = data[header_end + 1:header_end + 1 + size]
        pos = header_end + 1 + size + 1
        kind, name = blobs[b]
        out[kind].setdefault(name, set()).add(hashlib.sha256(body).hexdigest())
    return out


def from_tree(plugin_root):
    out = {k: {} for k in KINDS}
    for vdir in sorted((plugin_root / "golden-thread").glob("*/templates")):
        for kind in KINDS:
            for f in sorted((vdir / kind).glob("*")):
                if f.is_file() and f.suffix != ".pyc":
                    out[kind].setdefault(f.name, set()).add(
                        hashlib.sha256(f.read_bytes()).hexdigest())
    return out


def from_file(target):
    """The list as it stands: a hash once listed is never dropped. A template edited again
    before its release is committed would otherwise lose the text some vault already got
    from an earlier build of that release (a dev install), and that copy would read as
    the owner's."""
    out = {k: {} for k in KINDS}
    try:
        old = json.loads(Path(target).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return out
    for kind in KINDS:
        for name, hs in (old.get(kind) or {}).items():
            out[kind][name] = set(hs)
    return out


def build(release_dir):
    release_dir = Path(release_dir).resolve()
    plugin_root = release_dir.parent.parent
    merged = {k: {} for k in KINDS}
    for part in (from_git(plugin_root), from_tree(plugin_root),
                 from_file(release_dir / "templates" / "shipped-hashes.json")):
        for kind in KINDS:
            for name, hs in part[kind].items():
                merged[kind].setdefault(name, set()).update(hs)
    return {
        "about": "sha256 of every vault tool and git hook gt has shipped; install.sh replaces "
                 "a vault copy only when it is listed here. Generated by dev/shipped_hashes.py.",
        **{kind: {n: sorted(hs) for n, hs in sorted(merged[kind].items())} for kind in KINDS},
    }


def main(argv):
    if not argv or argv[0].startswith("-"):
        print(__doc__.strip().splitlines()[-2].strip())
        return 2
    release_dir = Path(argv[0])
    target = release_dir / "templates" / "shipped-hashes.json"
    want = json.dumps(build(release_dir), indent=1) + "\n"
    if "--check" in argv[1:]:
        have = target.read_text(encoding="utf-8") if target.is_file() else ""
        if have != want:
            print("stale: %s — run dev/shipped_hashes.py %s" % (target, release_dir))
            return 1
        print("ok: %s" % target)
        return 0
    target.write_text(want, encoding="utf-8")
    print("wrote %s" % target)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
