#!/usr/bin/env bash
# release.sh -- this project's release pipeline: the steps in release-pipeline.tsv, in order.
#
# A required step that fails stops the run; a step exiting 99 is not applicable here (SKIP).
# Change the steps with gt_pipeline.py add / set / remove, which re-render this file.
#
# GENERATED by gt_recipe.py from release-pipeline.tsv (recipe sha256 fa82e566b86182f2).
# Do not edit this file: edit the recipe, then run
#   gt_recipe.py render release-pipeline.tsv --out release.sh
# (`gt_recipe.py check` fails while this file and its recipe disagree.)
set -uo pipefail
GT_RECIPE_SHA=fa82e566b86182f2
GT_DRY=no; GT_LIST=no; GT_UNTIL=""; GT_FROM=""; GT_GO=no
usage() {
  cat <<'GT_USAGE'
./release.sh [--list] [--dry-run] [--until ID] [--from ID] [--go]

  --list        print the steps in run order and exit
  --dry-run     say what each step would run; run nothing
  --until ID    stop BEFORE step ID (e.g. --until owner-gate)
  --from ID     start at step ID
  --go          the owner's explicit go-ahead, for the owner-gate step
GT_USAGE
}
GT_STEPS=(tests allin branch install owner-gate push sync)
GT_G_tests='the test suite passed and a receipt was recorded'
GT_K_tests=step
GT_R_tests=yes
GT_C_tests='gt_builtin tests'
GT_G_allin='every gt-allin check ran: scan, credentials, lint, validations'
GT_K_allin=gate
GT_R_allin=yes
GT_C_allin='gt_builtin allin'
GT_G_branch='the work is on a branch, never the default branch'
GT_K_branch=gate
GT_R_branch=yes
GT_C_branch='gt_builtin branch'
GT_G_install='installed, and the post-install validation passed'
GT_K_install=step
GT_R_install=yes
GT_C_install='gt_builtin install'
GT_G_owner_gate='the owner gave an explicit go-ahead'
GT_K_owner_gate=gate
GT_R_owner_gate=yes
GT_C_owner_gate='gt_builtin owner-gate'
GT_G_push='the branch is on the remote others read'
GT_K_push=step
GT_R_push=yes
GT_C_push='gt_builtin push'
GT_G_sync='every downstream copy is updated'
GT_K_sync=step
GT_R_sync=yes
GT_C_sync='gt_builtin sync'
list_steps() {
  local i=0 v g k q
  for id in "${GT_STEPS[@]}"; do
    i=$((i+1)); v=${id//-/_}; g=GT_G_$v; k=GT_K_$v; q=GT_R_$v
    printf '%2d. %-14s %-5s required=%-3s %s\n' "$i" "$id" "${!k}" "${!q}" "${!g}"
  done
}
while [ $# -gt 0 ]; do
  case "$1" in
    --list) GT_LIST=yes; shift ;;
    --dry-run) GT_DRY=yes; shift ;;
    --until) [ $# -ge 2 ] || { echo "REFUSED: --until needs a step id"; exit 2; }; GT_UNTIL="$2"; shift 2 ;;
    --from) [ $# -ge 2 ] || { echo "REFUSED: --from needs a step id"; exit 2; }; GT_FROM="$2"; shift 2 ;;
    --go) GT_GO=yes; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1"; usage; exit 2 ;;
  esac
done
REPO="$(cd "$(dirname "$0")" && pwd -P)"
cd "$REPO"
gt_find() {
  local name="$1" var="$2" c
  if [ -n "${!var:-}" ] && [ -f "${!var}" ]; then echo "${!var}"; return 0; fi
  c=$(ls -d "$HOME"/.claude/plugins/cache/*/gt/*/scripts/"$name" 2>/dev/null | sort -V | tail -1)
  [ -n "$c" ] && echo "$c"
}
gt_builtin() {
  local p
  p=$(gt_find gt_pipeline.py GT_PIPELINE_PY) || true
  if [ -z "$p" ]; then echo "  cannot run @$1: gt_pipeline.py not found (install gt, or set GT_PIPELINE_PY)"; return 1; fi
  GT_OWNER_GO="$GT_GO" python3 "$p" builtin "$1" --repo "$REPO"
}
gt_metric() {
  [ "${GT_EXECUTION_METRICS:-on}" = off ] && return 0
  local m
  m=$(gt_find gt_metrics.py GT_METRICS_PY) || return 0
  [ -n "$m" ] || return 0
  python3 "$m" record --repo "$REPO" --process "$1" --duration "$2" --exit "$3" --trait pipeline >/dev/null 2>&1 || true
}
gt_now() { python3 -c "import time; print(time.time())"; }
gt_secs() { python3 -c "import sys; print('%.1f' % (float(sys.argv[2]) - float(sys.argv[1])))" "$1" "$2"; }
step_tests() {
gt_builtin tests
}
step_allin() {
gt_builtin allin
}
step_branch() {
gt_builtin branch
}
step_install() {
gt_builtin install
}
step_owner_gate() {
gt_builtin owner-gate
}
step_push() {
gt_builtin push
}
step_sync() {
gt_builtin sync
}
if [ "$GT_LIST" = yes ]; then list_steps; exit 0; fi
gt_known() { local x; for x in "${GT_STEPS[@]}"; do [ "$x" = "$1" ] && return 0; done; return 1; }
for _f in "$GT_UNTIL" "$GT_FROM"; do
  if [ -n "$_f" ] && ! gt_known "$_f"; then echo "REFUSED: no step named $_f"; list_steps; exit 2; fi
done
GT_RAN=(); GT_SKIPPED=(); GT_WARNED=(); GT_NOT=(); GT_STARTED=no; GT_STOPPED=no
[ -z "$GT_FROM" ] && GT_STARTED=yes
GT_T0=$(gt_now)
for id in "${GT_STEPS[@]}"; do
  v=${id//-/_}
  if [ "$GT_STOPPED" = yes ] || [ "$id" = "$GT_UNTIL" ]; then GT_STOPPED=yes; GT_NOT+=("$id"); continue; fi
  if [ "$GT_STARTED" = no ]; then
    if [ "$id" = "$GT_FROM" ]; then GT_STARTED=yes; else GT_NOT+=("$id"); continue; fi
  fi
  _g=GT_G_$v; _r=GT_R_$v; _c=GT_C_$v; g="${!_g}"; req="${!_r}"; cmd="${!_c}"
  if [ "$GT_DRY" = yes ]; then printf "would run  %-14s %s\n" "$id" "$cmd"; continue; fi
  echo "== $id: $g"
  t=$(gt_now)
  set +e
  ( "step_$v" )
  rc=$?
  s=$(gt_secs "$t" "$(gt_now)")
  gt_metric "release:$id" "$s" "$rc"
  if [ "$rc" -eq 0 ]; then printf "ok     %-14s %6ss\n" "$id" "$s"; GT_RAN+=("$id")
  elif [ "$rc" -eq 99 ]; then printf "SKIP-not-applicable %-14s\n" "$id"; GT_SKIPPED+=("$id")
  elif [ "$req" = no ]; then printf "FAIL   %-14s %6ss  (exit %s; optional, continuing)\n" "$id" "$s" "$rc"; GT_RAN+=("$id"); GT_WARNED+=("$id")
  else
    printf "FAIL   %-14s %6ss  (exit %s)\n" "$id" "$s" "$rc"
    GT_RAN+=("$id"); GT_STOPPED=yes; GT_FAILED="$id"
  fi
done
[ "$GT_DRY" = yes ] && { echo "(dry run: nothing was run)"; exit 0; }
GT_TOTAL=$(gt_secs "$GT_T0" "$(gt_now)")
echo ""
echo "ran ${#GT_RAN[@]} of ${#GT_STEPS[@]} step(s) in ${GT_TOTAL}s: ${GT_RAN[*]:-none}"
[ ${#GT_SKIPPED[@]} -gt 0 ] && echo "not applicable: ${GT_SKIPPED[*]}"
[ ${#GT_WARNED[@]} -gt 0 ] && echo "optional steps that failed: ${GT_WARNED[*]}"
[ ${#GT_NOT[@]} -gt 0 ] && echo "not run: ${GT_NOT[*]}"
if [ -n "${GT_FAILED:-}" ]; then gt_metric release "$GT_TOTAL" 1; echo "STOPPED at the first failure: $GT_FAILED"; exit 1; fi
gt_metric release "$GT_TOTAL" 0
exit 0
