#!/usr/bin/env python3
"""Per-session spool files, and the deterministic merge that renders them.

## Why this exists

`log.md` and `decisions.md` are append-only, shared, and live in ONE working tree.
There are no branches to collide and no merge to resolve -- just last-writer-wins,
invisible at the moment it happens. On 2026-09-10 a session appended one line to
`log.md` and committed it, carrying NINE lines written by earlier sessions that
happened to be uncommitted in the shared tree. Nothing was lost, but "commit only
your own files" is unenforceable while everyone's work is in one file.

Claims do not help here. `gt_session.py` claims are advisory by design -- in one
working tree a stuck lock is worse than the corruption it prevents -- and
`guard_session_claims` inspects `Write`/`Edit` while `log.md` is appended with `>>`
and `tee`, which it deliberately does not see. The protection that exists does not
cover the file that needs it most.

So this removes the shared write target instead of arbitrating access to it. Every
session appends to a file only it writes; the shared file is RENDERED from them, the
way `TASKS.md` is already rendered rather than edited.

## The baseline is what makes adoption safe

Migration copies the existing `log.md` (or `decisions.md`) into `0000-baseline.md`,
which sorts first and is never written again. No history is rewritten, no past
session has to be reconstructed, and nothing is renumbered. The gate on migration is
a BYTE-IDENTICAL round trip: if the merge cannot reproduce the original file exactly,
the design is wrong and nothing is committed.

## Ordering is total and machine-independent

Two machines merging the same spools must produce byte-identical output, or the
GENERATED file starts conflicting in git -- worse than the problem being solved. So
the sort key uses nothing that varies by machine: no mtimes, no directory order, no
locale. Baseline first, then (timestamp, session-id, index-within-that-session).
Minute-resolution timestamps collide often, so the session id is doing real work as
the second key, and the index preserves a session's own order.
"""
import hashlib
import os
import re
import sys
import tempfile
from pathlib import Path

BASELINE = "0000-baseline.md"
BANNER = ("<!-- GENERATED by gt_log.py / gt_adr.py from Projects/golden-thread/spool/. "
          "Do not hand-edit: your change is lost at the next merge. "
          "Add entries with the tool; run `merge` to regenerate. -->")

# A leading `YYYY-MM-DD` with an optional `HH:MM` and zone. Kept deliberately loose:
# the sort must not depend on a session having written the optional parts, and a line
# that carries no date at all still has to sort somewhere stable rather than crash.
STAMP = re.compile(r"^(\d{4}-\d{2}-\d{2})(?:\s+(\d{2}:\d{2}))?")

# Owner files are not guaranteed UTF-8 (a latin-1 `\xe9` in a years-old log.md is real).
# Until 0.15.0 they were read with errors="replace", which wrote U+FFFD into the baseline
# and the generated file -- and the round-trip gate compared two already-replaced copies,
# so it passed. surrogateescape maps every undecodable byte to a lone surrogate and back,
# so read -> render -> write is byte-identical for ANY input, and str equality means byte
# equality. Every read that can flow into a write, and every such write, uses it.
OWNER_ERRORS = "surrogateescape"


def read_owner(path):
    """Text of an owner file whose bytes must survive a round trip unchanged."""
    return Path(path).read_text(encoding="utf-8", errors=OWNER_ERRORS)


def owner_bytes(text):
    """Bytes of `text` read with read_owner -- the inverse, undecodable bytes restored."""
    return text.encode("utf-8", OWNER_ERRORS)


def session_id(explicit=None):
    """The current session id, resolved exactly as gt_session.py resolves it.

    Reused rather than reinvented so a spool file and a session claim name the same
    session -- `gt_session.py list` can then say whether the owner of an unfinished
    allocation is still alive.
    """
    if explicit:
        return explicit
    for var in ("CLAUDE_CODE_SESSION_ID", "CLAUDE_SESSION_ID", "GT_SESSION_ID"):
        v = os.environ.get(var)
        if v:
            return re.sub(r"[^A-Za-z0-9._-]", "-", v)[:80]
    return "unknown-%d" % os.getpid()


def vault_root(explicit=None):
    """Resolve the vault: --vault, then $GT_VAULT, then ~/.claude/vault-config.json."""
    if explicit:
        return Path(explicit).expanduser().resolve()
    if os.environ.get("GT_VAULT"):
        return Path(os.environ["GT_VAULT"]).expanduser().resolve()
    import json
    cfg = Path.home() / ".claude" / "vault-config.json"
    try:
        p = json.loads(cfg.read_text(encoding="utf-8")).get("vault_path")
    except Exception:
        p = None
    if not p:
        raise SystemExit("no vault: pass --vault, set GT_VAULT, or run /gt:gt-init")
    return Path(p).expanduser().resolve()


def spool_dir(vault, kind, project=None):
    """`<vault>/Projects/golden-thread/spool/<kind>[/<project>]`."""
    d = Path(vault) / "Projects" / "golden-thread" / "spool" / kind
    if project:
        d = d / project
    return d


def _load_safe_write():
    """The safe_write module sitting beside us, or None in a vault that predates it.

    ONLY the loading may fail quietly. Until 0.16.5 the whole call -- load AND write --
    sat under `except Exception: pass` and fell through to a plain append, so
    safe_write's central promise (it refuses rather than replacing a file it cannot
    read) was caught, discarded, and the write it had just refused was retried
    unguarded. A fallback for "this vault has no safe_write.py" must not double as a
    fallback for "safe_write said no".
    """
    sw = Path(__file__).resolve().parent / "safe_write.py"
    if not sw.is_file():
        return None
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location("_sw", str(sw))
        m = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(m)
        return m
    except Exception:
        return None


def _safe_write(target, text):
    """Append `text` to `target` through safe_write.py when it is beside us.

    -> the strategy name safe_write used ("direct", "atomic", "direct-degraded"), or
    "direct" for the fallback. RAISES if the bytes did not reach `target`.

    A spool file has exactly one writer, so an in-place append is the right primitive:
    O(new bytes), atomic per call at line sizes, and it never rewrites bytes it did not
    author (safe_write's own strategy 0, and the 0.9.6 lesson recorded in its
    docstring). The fallback for a vault whose tools predate safe_write.py is therefore
    that same plain in-place append -- NOT an atomic whole-file replace, which the
    docstring wrongly promised through 0.16.4 while the code appended.

    What the fallback is not allowed to be is a second attempt at a write safe_write
    already declined; see _load_safe_write. And safe_write's return value is checked
    rather than dropped: its sidecar and ledger-dir strategies leave the bytes NEXT TO
    the spool with a `mv` queued in the ledger, so a caller that ignored the return
    reported a spooled entry that the next merge would not render.
    """
    target = Path(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    m = _load_safe_write()
    if m is not None:
        res = m.write(str(target), text, "a" if target.exists() else "w")
        wrote, strategy = (res if isinstance(res, tuple) else (res, "unknown"))
        if os.path.realpath(str(wrote)) != os.path.realpath(str(target)):
            raise OSError(
                "gt_spool: the entry did NOT reach %s -- safe_write fell back to the %s "
                "strategy and left it at %s. Nothing is spooled until that move lands; "
                "run `python3 safe_write.py replay` once the destination is writable."
                % (target, strategy, wrote))
        return strategy
    with open(target, "a", encoding="utf-8") as fh:
        fh.write(text)
    return "direct"


def append(vault, kind, text, project=None, sid=None):
    """Append one entry to THIS session's spool file. Never touches a shared file."""
    sid = session_id(sid)
    d = spool_dir(vault, kind, project)
    d.mkdir(parents=True, exist_ok=True)
    if not text.endswith("\n"):
        text += "\n"
    p = d / ("%s.md" % sid)
    _safe_write(p, text)
    return p


def roundtrip_note(produced_body, original):
    """Is the rendered body faithful to the original? -> "" identical, str note, None no.

    The migration gate claims a byte-identical round trip. Until 0.12.0 both sides
    were compared with `rstrip("\\n")`, so a file ending in a blank line passed the
    gate and was then written WITHOUT that line: on 2026-09-11 migrating 42 projects
    silently dropped one from `homekit-bridge/decisions.md`. A gate that normalises
    the thing it is checking is not a gate.

    Trailing blank lines are still not worth refusing a migration over -- so the
    difference is ANNOUNCED and the caller prints it, rather than tolerated in
    silence. Any other difference still refuses.
    """
    if produced_body == original:
        return ""
    if produced_body.rstrip("\n") != original.rstrip("\n"):
        return None
    lost = len(original) - len(original.rstrip("\n"))
    kept = len(produced_body) - len(produced_body.rstrip("\n"))
    delta = lost - kept
    if delta > 0:
        return " (dropped %d trailing blank line(s) the original ended with)" % delta
    return " (added %d trailing blank line(s))" % -delta


def _sort_key(fname, index, line):
    """Baseline first, then (timestamp, session id, index within that file).

    Every component is stable across machines. `index` keeps a single session's own
    entries in the order it wrote them even when their timestamps are identical,
    which at minute resolution is the common case rather than the rare one.
    """
    if fname == BASELINE:
        return (0, "", "", index)
    m = STAMP.match(line)
    stamp = (m.group(1) + " " + (m.group(2) or "")) if m else ""
    return (1, stamp, fname, index)


def lines(vault, kind, project=None):
    """Every spooled line, in merge order. Blank lines are preserved inside a file."""
    d = spool_dir(vault, kind, project)
    if not d.is_dir():
        return []
    out = []
    for f in sorted(d.iterdir()):
        if not f.is_file() or f.suffix != ".md":
            continue
        try:
            body = read_owner(f)
        except OSError:
            continue
        for i, ln in enumerate(body.splitlines()):
            out.append((_sort_key(f.name, i, ln), ln))
    out.sort(key=lambda t: t[0])
    return [ln for _, ln in out]


# The third outcome of write_if_changed: the file on disk is no longer the file the
# caller decided about, so nothing was written. A distinct value rather than an
# exception or a bare False, because "unchanged (idempotent)" and "someone else moved
# underneath you" are different things and only the caller knows what to do about the
# second one. Truthy, so a caller that ignores it never reports a silent success.
STALE = "stale"


def content_digest(data):
    """Digest of owner bytes -- accepts the text a caller rendered, or raw bytes.

    Only ever compared against another digest from this function, so the algorithm is
    an implementation detail; sha256 because it is in the stdlib and collisions here
    would mean silently overwriting someone's save.
    """
    if isinstance(data, str):
        data = owner_bytes(data)
    return hashlib.sha256(data).hexdigest()


def _as_digest(expect):
    """Normalise the caller's `expect` -- a digest from content_digest, or the content.

    A 64-character hex string is a digest (content_digest's own output); anything else
    is content to be digested. Passing bytes or str content is the convenient form for
    a caller that already holds the snapshot it decided on.
    """
    if isinstance(expect, str) and len(expect) == 64 and re.fullmatch(r"[0-9a-f]{64}", expect):
        return expect
    return content_digest(expect)


class Unreadable(OSError):
    """`target` EXISTS but cannot be read, so nothing may be written over it.

    The third state, and until 0.16.5 the missing one. `current_digest` answered
    `content_digest(b"")` on ANY OSError and `write_if_changed` set `current = None` on
    any OSError, so a file that existed and could not be read digested exactly like a
    file that was not there: `before == expect` held, the precondition reported "nobody
    moved underneath you" about a file nobody could see, `hand_written()` returned []
    (its `is_generated` swallows the same OSError), and the render replaced it.

    REPRODUCED on 0.16.4: `chmod 000 log.md; gt_log.py merge` printed "log.md updated",
    exited 0, and the hand-written line was gone -- with no warning and no rescue file.
    0.16.4 also made it permanent, because mode preservation (correct in itself) copies
    mode 000 onto the replacement, so every later merge clobbers it again and idempotence
    is broken for good; 0.16.3's plain open() left the replacement 0644, so the damage
    was one-shot.

    The trigger is ordinary -- an ACL glitch, a sync client mid-state, a file owned by
    another uid -- so this follows safe_write.py's rule verbatim: refuse rather than
    replace a file we cannot read. It is an exception rather than a sentinel because the
    callers that must not mistake it for success include ones that pass two arguments and
    read the result as a bool.
    """


def read_bytes_or_none(path):
    """Bytes of `path`; None when it is genuinely ABSENT; Unreadable when it is neither.

    The absence test is the READ, never `os.path.exists`, for the reason safe_write
    records: `exists()` answers False for "I cannot tell" as well as for "not there", so
    a file whose parent cannot be traversed reports False while holding content. Only
    FileNotFoundError means absent.
    """
    try:
        return Path(path).read_bytes()
    except FileNotFoundError:
        return None
    except OSError as exc:
        raise Unreadable(
            "%s exists but cannot be read (%s: %s) — refusing rather than replacing a "
            "file whose contents nobody can see" % (path, type(exc).__name__, exc))


def current_digest(target):
    """Digest of `target` as it is right now; a file that is not there digests as empty.

    Absent-is-empty matches how every caller reads the target before deciding (`read_owner
    if it exists else ""`), so "the file appeared underneath me" is a mismatch, not a crash.
    An UNREADABLE target is the one case that is neither: it raises `Unreadable`, because
    digesting it as empty is what made the 0.16.4 data loss silent.
    """
    raw = read_bytes_or_none(target)
    return content_digest(b"" if raw is None else raw)


def write_if_changed(target, text, expect=None):
    """Replace `target` only when the bytes differ -> True written, False identical.

    Idempotence is an acceptance criterion, not a nicety: a merge that rewrites an
    unchanged file makes every session's `git status` dirty and re-teaches people to
    ignore it.

    ## The temp file must not be a shared name

    Until 0.16.4 the temp path was `<target>.gt-tmp` -- deterministic, so two merges
    running at once (several sessions open in one vault is the normal state here, and
    `gt_log.py add` merges by default) used the SAME scratch file. One truncates the
    other's half-written bytes, and whichever `os.replace` lands second renders a
    mixture, or a fd still being written to, into the shared file. That is the exact
    corruption the spool exists to remove, reintroduced one level down. `mkstemp` in
    the target's own directory gives each writer a private name, on the same filesystem
    so the replace stays atomic; it is unlinked again if anything below it fails, so a
    crashed merge leaves no `.gt-tmp` litter beside a vault file.

    ## `expect` closes the read-decide-write window

    A caller decides what to write from a snapshot it read earlier -- `gt_log.py` runs
    `hand_written()` over the target and only THEN calls this, which re-reads and
    replaces. A human save landing between those two reads is lost, and it is lost
    precisely in the mechanism that exists to rescue hand-written lines. A caller that
    passes the digest (or the content) it decided on gets STALE instead of a clobbered
    file, and can re-read and decide again. `expect=None` keeps the pre-0.16.4
    behaviour exactly, and is still the live contract: `gt_log.py merge` and
    `gt_adr.py merge` pass `expect=`, but their `migrate` paths and `gt_events.py` call
    this with two arguments and must keep working unchanged.

    ## An unreadable target is refused, not treated as absent

    Reading the target used to swallow every OSError into `current = None`, which is
    also what a file that is not there gives -- so a file that existed and could not be
    read passed the precondition and was replaced. It now raises `Unreadable` before
    anything is written. See that class.
    """
    target = Path(target)
    new = owner_bytes(text)
    current = read_bytes_or_none(target)
    if expect is not None and content_digest(b"" if current is None else current) != _as_digest(expect):
        return STALE
    if current == new:
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    # Keep the target's own permissions: mkstemp creates 0600, and a log.md that
    # quietly became owner-only after a merge is a change nobody asked for.
    try:
        mode = target.stat().st_mode & 0o7777
    except OSError:
        mode = None
    fd, tmp = tempfile.mkstemp(dir=str(target.parent), prefix=target.name + ".", suffix=".gt-tmp")
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(new)
            fh.flush()
            os.fsync(fh.fileno())
        if mode is not None:
            os.chmod(tmp, mode)
        os.replace(tmp, target)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    return True


def hand_written(target, rendered):
    """Lines in the generated `target` that `rendered` does not produce -> [str].

    The banner says "do not hand-edit", but people do, and until 0.15.0 the next render
    (any `gt_log.py add`, including the receipt install.sh writes) deleted those lines
    with no word. A line counts when the current file has it and a render of the spool
    does not: it was typed into the file, or a generated line was changed by hand. Blank
    lines and the banner are ignored; a file that is not generated returns nothing (the
    callers refuse those before rendering)."""
    import difflib
    target = Path(target)
    if not target.is_file() or not is_generated(target):
        return []
    current = read_owner(target)
    if current == rendered:
        return []
    cur, new = current.splitlines(), rendered.splitlines()
    out = []
    for op, i1, i2, _j1, _j2 in difflib.SequenceMatcher(None, cur, new,
                                                        autojunk=False).get_opcodes():
        if op in ("delete", "replace"):
            out.extend(l for l in cur[i1:i2] if l.strip() and "GENERATED by" not in l)
    return out


def capture_hand_written(vault, kind, found, project=None):
    """Keep hand-written lines by spooling them -> the spool file written.

    They go into `hand-edits-<UTC time>.md` in the same spool, verbatim and in their
    order, so every later render carries them. Where a line lands follows the merge
    order like any spooled line: a line starting with a date sorts by that date (a log
    entry lands where it was); a line with no date sorts straight after the baseline.

    ## Every call adds the lines AGAIN -- once-only is the caller's to guarantee

    This is an append, not a reconciliation: it cannot tell a line the caller has
    already rescued from a second, genuinely new hand edit that happens to read the
    same. `gt_log.cmd_merge` retries its decision up to three times and MUST NOT hand
    the same line over twice; it keeps its own tally of what it has captured. (Through
    0.16.4 it did not, and a single stale attempt duplicated every rescued line in the
    spool -- permanently, since the spool IS the audit trail and a re-merge renders what
    it finds.)

    The file is created EXCLUSIVELY, falling back to `-1`, `-2`, ... on collision.
    Opening `"ab"` on a name that is only second-resolution meant two captures inside
    one second landed in one file, indistinguishable afterwards; distinct files keep the
    two captures separable, and the names still sort deterministically on every machine."""
    import time
    d = spool_dir(vault, kind, project)
    d.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
    data = owner_bytes("".join(l + "\n" for l in found))
    for n in range(1000):
        p = d / ("hand-edits-%s%s.md" % (stamp, "" if n == 0 else "-%d" % n))
        try:
            with open(p, "xb") as fh:
                fh.write(data)
            return p
        except FileExistsError:
            continue
    raise OSError("gt_spool: cannot find a free hand-edits name in %s" % d)


def is_generated(path):
    """True when `path` carries the generated banner.

    Answers False for a file it cannot read, which is deliberately NOT a licence to
    write: the callers use it only to refuse (an un-generated target with no baseline),
    and every write path goes through `read_bytes_or_none`, which raises `Unreadable`
    rather than letting "I could not look" pass as "there is nothing there".
    """
    try:
        return BANNER.split("GENERATED")[0] + "GENERATED" in Path(path).read_text(
            encoding="utf-8", errors="replace")[:600]
    except OSError:
        return False
