#!/usr/bin/env python3
"""gt_write_queue.py -- ask for a vault write instead of making it; gt_broker.py applies it.

    gt_write_queue.py --vault V --path REL --op append|replace-section|create
                      (--content TEXT | --content-file F) [--section HEADING]
                      [--session ID] [--origin session|farm] [--hint TEXT] [--dry-run] [--json]

WHY THIS EXISTS. Every session shares one working tree, so two writers to one vault file are a
last-writer-wins overwrite with nothing to show for it (PROTOCOL.md, "Concurrent sessions").
Core rule 1 closes the common case -- a session claims a file before editing it -- but an agent
running outside the claiming session (a farmed result coming back, a batch of subagents all
filing findings) has no claim and no way to wait for one. This tool gives such a writer a place
to put its write: one JSON request file per write in

    <vault>/Projects/golden-thread/spool/queue/<UTC timestamp>-<session>-<target>.json

and nothing else. It never touches the target. `gt_broker.py drain` applies the queue later, in
timestamp order, after checking claims and conflicts; see that tool for what it decides.

A session that holds its claim and writes directly is unaffected. The queue is additive.

OPERATIONS (a section is a level-2 heading, `## <heading>`, matched case-insensitively):

    append            add CONTENT at the end of SECTION (or of the file, with no --section);
                      a missing section is created at the end of the file
    replace-section   replace SECTION's body with CONTENT. The section's current hash is
                      recorded now, so the broker can tell if anyone changed it in between
    create            a new file; refused at drain time if the file exists with other content

WHAT IT REFUSES, here and again at drain time: a path outside the vault, a path with a `..` or
a dot-segment, anything but a `.md` file, and the files other tools own -- `log.md`,
`TASKS.md`, every `decisions.md` (all generated), `Sources/` (immutable), the Core rules, and
gt's own `sessions/`, `spool/` and `tools/`. `--origin extension` does not exist: under ADR-8
and design-write-broker.md v1 a third-party extension has no write path at all.

Exit: 0 queued (or would be, with --dry-run) | 1 refused | 2 usage.
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import os
import re
import sys
import tempfile
from pathlib import Path

SCHEMA = 1
QUEUE_REL = Path("Projects") / "golden-thread" / "spool" / "queue"
OPS = ("append", "replace-section", "create")
ORIGINS = ("session", "farm")
MAX_CONTENT = 256 * 1024
KEYS = {"schema", "id", "submitted", "session", "origin", "path", "op", "section", "content",
        "base_sha256", "hint"}

# Files another tool owns. A write here would be lost (generated files are rebuilt from their
# spool) or would break a rule (Sources are immutable; Core rules are re-asserted every turn).
GENERATED_NAMES = {"decisions.md"}
REFUSED_EXACT = {"log.md", "TASKS.md"}
REFUSED_PREFIXES = ("Sources/", "core-rules/", "Projects/golden-thread/core-rules/",
                    "Projects/golden-thread/sessions/", "Projects/golden-thread/spool/",
                    "Projects/golden-thread/tools/")

HEADING = re.compile(r"^##\s+(.+?)\s*#*\s*$")
ANY_TOP = re.compile(r"^#{1,2}\s")
FENCE = re.compile(r"^\s*(```|~~~)")


# ---------------------------------------------------------------- vault + paths ----

def find_vault(explicit: str | None) -> Path | None:
    """--vault, then $GT_VAULT, then vault_path in ~/.claude/vault-config.json."""
    cand = explicit or os.environ.get("GT_VAULT")
    if not cand:
        try:
            cand = json.loads((Path.home() / ".claude" / "vault-config.json")
                              .read_text(encoding="utf-8")).get("vault_path")
        except Exception:
            cand = None
    if not cand:
        return None
    p = Path(cand).expanduser()
    return p if p.is_dir() else None


def queue_dir(vault: Path) -> Path:
    return vault / QUEUE_REL


def path_refusal(vault: Path, rel: str) -> str | None:
    """-> why this vault-relative path may not be written through the queue, or None."""
    if not isinstance(rel, str) or not rel.strip():
        return "no path given"
    if "\\" in rel or "\0" in rel or rel.startswith("/") or re.match(r"^[A-Za-z]:", rel):
        return "the path must be relative to the vault, with forward slashes"
    parts = rel.split("/")
    if any(p in ("", ".", "..") or p.startswith(".") for p in parts):
        return "the path may not contain empty, `.`, `..` or dot-prefixed segments"
    if not rel.endswith(".md"):
        return "only Markdown (.md) files are written through the queue"
    if rel in REFUSED_EXACT:
        return "%s is generated by its own tool; never written by hand or by the broker" % rel
    if parts[-1] in GENERATED_NAMES:
        return ("decisions.md is generated from spool/decisions/ -- allocate an ADR with "
                "gt_adr.py instead")
    for pre in REFUSED_PREFIXES:
        if rel.startswith(pre):
            return "%s is owned by another tool or rule and is never written through the queue" % pre
    try:
        root = os.path.realpath(vault)
        real = os.path.realpath(os.path.join(root, *parts))
        if os.path.commonpath([root, real]) != root:
            return "the path resolves outside the vault"
    except ValueError:
        return "the path resolves outside the vault"
    return None


# ---------------------------------------------------------------------- sections ----

def split_lines(text: str) -> list[str]:
    return text.replace("\r\n", "\n").split("\n") if text else []


def find_section(lines: list[str], section: str):
    """-> (heading index, end index exclusive) of the first `## section`, or None. Headings
    inside fenced code blocks are not headings."""
    want = section.strip().lower()
    fenced, start = False, None
    for i, line in enumerate(lines):
        if FENCE.match(line):
            fenced = not fenced
            continue
        if fenced:
            continue
        if start is not None and ANY_TOP.match(line):
            return start, i
        m = HEADING.match(line)
        if start is None and m and m.group(1).strip().lower() == want:
            start = i
    return (start, len(lines)) if start is not None else None


def section_body(lines: list[str], section: str) -> str | None:
    rng = find_section(lines, section)
    if rng is None:
        return None
    return "\n".join(lines[rng[0] + 1:rng[1]]).strip("\n")


def sha(text: str | None) -> str | None:
    return None if text is None else hashlib.sha256(text.encode("utf-8")).hexdigest()


def current_base(vault: Path, rel: str, section: str | None) -> str | None:
    """Hash of what replace-section would replace, as it stands now. None = absent."""
    try:
        text = (vault / rel).read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    return sha(section_body(split_lines(text), section)) if section else sha(text)


# ---------------------------------------------------------------------- requests ----

def session_id(explicit: str | None) -> str:
    if explicit:
        return explicit.strip()
    for var in ("CLAUDE_CODE_SESSION_ID", "CLAUDE_SESSION_ID", "GT_SESSION_ID"):
        if os.environ.get(var):
            return os.environ[var].strip()
    return "anonymous"


def _slug(text: str, n: int) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "-", text).strip("-").lower()
    return (s[:n].strip("-") or "x")


def validate(req: dict, vault: Path) -> str | None:
    """-> why this request is malformed or not allowed, or None. Used at submit AND drain:
    a request file is data on disk, and anything on disk may have been written by hand."""
    if not isinstance(req, dict):
        return "not a JSON object"
    extra = set(req) - KEYS
    if extra:
        return "unknown field(s): %s" % ", ".join(sorted(extra))
    if req.get("schema") != SCHEMA:
        return "unsupported schema %r" % req.get("schema")
    for k in ("id", "submitted", "session", "origin", "path", "op", "content"):
        if not isinstance(req.get(k), str):
            return "field %s missing or not a string" % k
    if req["op"] not in OPS:
        return "unknown op %r" % req["op"]
    if req["origin"] not in ORIGINS:
        return ("unknown origin %r -- a third-party extension has no write path (ADR-8)"
                % req["origin"])
    sec = req.get("section")
    if sec is not None and (not isinstance(sec, str) or not sec.strip() or "\n" in sec):
        return "section must be one non-empty line"
    if req["op"] == "replace-section" and sec is None:
        return "replace-section needs a section"
    if req["op"] == "create" and sec is not None:
        return "create takes no section"
    for k in ("base_sha256", "hint"):
        if req.get(k) is not None and not isinstance(req.get(k), str):
            return "field %s must be a string" % k
    if not req["content"].strip():
        return "empty content"
    if "\0" in req["content"] or len(req["content"].encode("utf-8")) > MAX_CONTENT:
        return "content is binary or larger than %d bytes" % MAX_CONTENT
    return path_refusal(vault, req["path"])


def build(vault: Path, rel: str, op: str, content: str, section: str | None, session: str,
          origin: str, hint: str | None, now: datetime.datetime | None = None) -> dict:
    now = now or datetime.datetime.now(datetime.timezone.utc)
    stamp = now.strftime("%Y%m%dT%H%M%S.%fZ")
    return {"schema": SCHEMA,
            "id": "%s-%s-%s" % (stamp, _slug(session, 8), _slug(rel, 60)),
            "submitted": now.isoformat(timespec="microseconds"),
            "session": session, "origin": origin, "path": rel, "op": op,
            "section": section, "content": content,
            "base_sha256": current_base(vault, rel, section) if op == "replace-section" else None,
            "hint": hint}


def deposit(vault: Path, req: dict) -> Path:
    """Write the request atomically. The temp name starts with `.` and does not end `.json`,
    so a concurrent drain never sees a half-written request."""
    q = queue_dir(vault)
    q.mkdir(parents=True, exist_ok=True)
    base, n = req["id"], 1
    while (q / (req["id"] + ".json")).exists():
        n += 1
        req["id"] = "%s-%d" % (base, n)
    fd, tmp = tempfile.mkstemp(prefix=".req.", suffix=".tmp", dir=str(q))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(req, fh, indent=1, ensure_ascii=False)
            fh.write("\n")
        dest = q / (req["id"] + ".json")
        os.replace(tmp, dest)
    except OSError:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    return dest


def pending(vault: Path) -> list[Path]:
    q = queue_dir(vault)
    try:
        return sorted(p for p in q.iterdir() if p.suffix == ".json" and not p.name.startswith("."))
    except OSError:
        return []


# -------------------------------------------------------------------------- CLI ----

def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="gt_write_queue.py", description=__doc__.split("\n\n")[0])
    ap.add_argument("--vault", help="the vault (default: $GT_VAULT, else vault-config.json)")
    ap.add_argument("--path", required=True, help="target file, relative to the vault")
    ap.add_argument("--op", required=True, choices=OPS)
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--content", help="the text to write")
    src.add_argument("--content-file", help="read the text from this file (`-` = stdin)")
    ap.add_argument("--section", help="level-2 heading the write targets (without `## `)")
    ap.add_argument("--session", help="originating session id (default: $CLAUDE_CODE_SESSION_ID)")
    ap.add_argument("--origin", default="session", choices=ORIGINS,
                    help="session (a Claude Code session or its agent) or farm (a farmed "
                         "result: only `create` is ever applied automatically)")
    ap.add_argument("--hint", help="one line for the owner if this request ends in a conflict")
    ap.add_argument("--dry-run", action="store_true", help="validate and show; queue nothing")
    ap.add_argument("--json", action="store_true")
    a = ap.parse_args(argv)

    vault = find_vault(a.vault)
    if vault is None:
        print("gt_write_queue: no vault found; pass --vault", file=sys.stderr)
        return 2
    if a.content is not None:
        content = a.content
    else:
        try:
            content = (sys.stdin.read() if a.content_file == "-"
                       else Path(a.content_file).read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError) as exc:
            print("gt_write_queue: could not read %s: %s" % (a.content_file, exc), file=sys.stderr)
            return 2
    hint = " ".join(a.hint.split()) if a.hint else None
    req = build(vault, a.path.strip(), a.op, content, a.section.strip() if a.section else None,
                session_id(a.session), a.origin, hint)
    why = validate(req, vault)
    if why:
        print("gt_write_queue: refused -- %s" % why, file=sys.stderr)
        return 1
    if a.dry_run:
        dest = queue_dir(vault) / (req["id"] + ".json")
        print(json.dumps(req, indent=1) if a.json else "would queue %s -> %s" % (
            a.op, dest.relative_to(vault)))
        return 0
    try:
        dest = deposit(vault, req)
    except OSError as exc:
        print("gt_write_queue: could not queue: %s" % exc, file=sys.stderr)
        return 1
    if a.json:
        print(json.dumps({"queued": str(dest), "id": req["id"]}))
    else:
        print("queued %s %s%s -> %s" % (a.op, req["path"],
                                        (" § " + req["section"]) if req["section"] else "",
                                        dest.relative_to(vault)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
