#!/usr/bin/env python3
"""gt_model_policy.py -- the model and effort each INSTALLED gt skill runs at (0.19.1).

    gt_model_policy.py table   [--profile P] [--vault V]       # what a profile means, printed
    gt_model_policy.py choose  P [--home H]                    # record the profile
    gt_model_policy.py current [--home H]                      # the recorded profile, or nothing
    gt_model_policy.py apply   [--profile P] [--agents-only] [--home H] [--vault V]
    gt_model_policy.py verify  [--home H]                      # exit 1 on a hand edit
    gt_model_policy.py set     (--skill S | --plugin P) --model M [--effort E] [--home H]
    gt_model_policy.py set     --agent A --model M [--effort E] [--home H]  # A: stage, job type or plugin:agent
    gt_model_policy.py clear   (--skill S | --plugin P | --agent A) [--home H]
    gt_model_policy.py show    [--home H] [--vault V] [--json]

Claude Code honours `model:` and `effort:` in a skill's frontmatter. gt writes them into the
INSTALLED copies only -- the plugin cache and the marketplace directory -- never the release
source, and records exactly what it wrote in ~/.claude/golden-thread/model-policy-applied.json,
so a later edit to the same field is told apart from gt's own work (`verify`).

Profiles (owner, 2026-10-02):
  average    the intent pack (gt_model): fast haiku with no effort, balanced sonnet medium,
             deep opus high. The shipped default for a new install.
  very-high  opus xhigh for every skill.
  inherit    nothing written: every skill runs on the session's model and effort, as before.

Resolution for one skill, highest first: the user's per-skill override, the per-plugin override,
the skill's model_intent through the profile, else inherit. An effort the model does not accept
is refused, never written (gt_model.effort_problem) -- Claude Code would lower it silently.

AGENTS ARE SET BY THE TASK, NOT THE PROFILE (owner, 2026-10-02: "doc reading doesn't need
opus"). A specialist agent (gt_agent_spec.py) runs at its spec's model_tier through the intent
pack -- fast haiku, standard sonnet, careful opus -- whichever profile the skills use, so a
very-high machine still reads documents on sonnet. The `agent_models` setting (task, the
default, or session) turns it off: session passes no model at all. Highest first: a per-agent override for the job type
(extract-docs), then for its stage (extract), then the tier.

AGENT DEFINITIONS CARRY THE EFFORT (0.20.1). gt ships one plugin agent per stage
(`agents/<stage>.md`, run as `gt:<stage>`, generated by `gt_agent_spec.py agents`), and its
frontmatter holds `model:` AND `effort:` -- the Agent tool's own `model` parameter takes no
effort, a definition does (Claude Code 2.1.78+). `apply` writes them into the INSTALLED agent
files exactly as it does for skills, from the same resolution: the tier through the intent pack
(fast haiku with no effort, standard sonnet medium, careful opus high), a stage override (model,
and effort when the model accepts one), or nothing at all under agent_models=session. A JOB-TYPE
override (extract-docs) is a model alias only: one file serves every kind of a stage, so that
job runs through the Agent tool's `model` with the session's effort, as before.

MODULE AGENTS (0.20.2). A module plugin may ship agent definitions of its own -- gt-lotr's
domain agents, run as `gt-lotr:jira` and so on: four READERS (model_intent fast, haiku) and four
WRITERS (`gt-lotr:jira-writer` ..., balanced, sonnet). Each one whose frontmatter declares a
`model_intent` is managed exactly like a stage agent: its intent through the intent pack (fast
haiku with no effort, balanced sonnet medium, deep opus high), whatever the skills' profile; a
per-agent override keyed by its full name (`set --agent gt-lotr:jira --model sonnet`, effort
allowed -- one file is one agent); nothing at all under agent_models=session. A definition
with no model_intent is left as shipped.
Exit: 0 ok, 1 a problem (refused combination, verify drift), 2 usage.
"""
import argparse
import json
import os
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.dont_write_bytecode = True
import gt_model  # noqa: E402

OK, PROBLEM, USAGE = 0, 1, 2
MARKET = "golden-thread-plugin"
PROFILES = ("average", "very-high", "inherit")
VERY_HIGH = ("opus", "xhigh")
AGENT_MODELS = ("haiku", "sonnet", "opus", "fable")   # what the Agent tool's `model` accepts
FIELDS = ("model", "effort")
# 0.20.2 first wrote a `writes_model:` line into module agent definitions. The reader/writer split
# made it redundant (a writer is its own agent with its own model_intent), so it is gone; a line a
# machine still carries from that build is stripped on the next rewrite.
LEGACY_KEYS = ("writes_model",)


def paths(home):
    home = Path(home or Path.home()).expanduser()
    return {"home": home,
            "choices": home / ".claude" / "golden-thread" / "install-choices.json",
            "record": home / ".claude" / "golden-thread" / "model-policy-applied.json",
            "installed": home / ".claude" / "plugins" / "installed_plugins.json",
            "market": home / ".claude" / "plugins" / "marketplaces" / MARKET / "plugins"}


def _load(p, default):
    try:
        return json.loads(Path(p).read_text(encoding="utf-8"))
    except Exception:
        return default


def _atomic(p, data):
    p = Path(p)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_name(p.name + ".tmp")
    tmp.write_bytes((json.dumps(data, indent=2) + "\n").encode("utf-8"))
    os.replace(tmp, p)


def model_choices(P):
    d = _load(P["choices"], {})
    m = d.get("model") if isinstance(d, dict) else None
    m = m if isinstance(m, dict) else {}
    return {"profile": m.get("profile"), "plugins": m.get("plugins") or {},
            "skills": m.get("skills") or {}, "agents": m.get("agents") or {}}


def _install_roots(entries):
    """-> [Path] of each installed_plugins.json entry's installPath. An entry with no
    installPath is skipped: Path("") is ".", and globbing it rewrote files in whatever directory
    the policy happened to run from (review m1/m2, 2026-10-04)."""
    roots = []
    for e in entries if isinstance(entries, list) else [entries]:
        r = str(e.get("installPath") or "") if isinstance(e, dict) else ""
        if r.strip():
            roots.append(Path(r))
    return roots


def installed_skills(P):
    """-> [(plugin, skill name, path)] for every installed copy of a gt-marketplace skill."""
    out = []
    data = _load(P["installed"], {})
    plugins = data.get("plugins", data) if isinstance(data, dict) else {}
    for key, entries in (plugins.items() if isinstance(plugins, dict) else []):
        name, _, market = key.partition("@")
        if market != MARKET:
            continue
        for root in _install_roots(entries):
            for f in sorted(root.glob("skills/*/SKILL.md")):
                out.append((name, f.parent.name, f))
        for f in sorted((P["market"] / name).glob("skills/*/SKILL.md")):
            out.append((name, f.parent.name, f))
    return out


AGENT_PLUGIN = "gt"     # the plugin whose agents/ hold the stage definitions


def installed_agents(P):
    """-> [(plugin, stage, path)] for every installed copy of a gt stage agent definition."""
    out = []
    data = _load(P["installed"], {})
    plugins = data.get("plugins", data) if isinstance(data, dict) else {}
    for key, entries in (plugins.items() if isinstance(plugins, dict) else []):
        name, _, market = key.partition("@")
        if market != MARKET or name != AGENT_PLUGIN:
            continue
        for root in _install_roots(entries):
            for f in sorted(root.glob("agents/*.md")):
                out.append((name, f.stem, f))
        for f in sorted((P["market"] / name).glob("agents/*.md")):
            out.append((name, f.stem, f))
    return out


def installed_module_agents(P):
    """-> [(plugin, "plugin:agent", path, intent)] for every installed copy of a MODULE plugin's
    agent definition that declares a model_intent (0.20.2). gt's own stage agents are
    installed_agents'; a definition with no model_intent is not the policy's to set."""
    out = []
    data = _load(P["installed"], {})
    plugins = data.get("plugins", data) if isinstance(data, dict) else {}
    for key, entries in (plugins.items() if isinstance(plugins, dict) else []):
        name, _, market = key.partition("@")
        if market != MARKET or name == AGENT_PLUGIN:
            continue
        for root in _install_roots(entries) + [P["market"] / name]:
            for f in sorted(root.glob("agents/*.md")):
                try:
                    intent = gt_model.read_intent(f)[0]
                except (OSError, UnicodeDecodeError):
                    continue
                if intent:
                    out.append((name, "%s:%s" % (name, f.stem), f, intent))
    return out


def resolve_one(plugin, skill, path, profile, choices, vault):
    """-> (model or None, effort or None, source). Raises ValueError on a refused effort."""
    for scope, key in (("skill", skill), ("plugin", plugin)):
        o = choices[scope + "s"].get(key)
        if isinstance(o, dict) and o.get("model"):
            bad = gt_model.effort_problem(o["model"], o.get("effort"))
            if bad:
                raise ValueError("%s override for %s: %s" % (scope, key, bad))
            return o["model"], o.get("effort"), "%s override" % scope
    if profile == "inherit":
        return None, None, "inherit"
    intent = gt_model.read_intent(path)[0]
    if intent not in gt_model.INTENTS:
        return None, None, "inherit (no model_intent)"
    if profile == "very-high":
        return VERY_HIGH[0], VERY_HIGH[1], "very-high profile"
    res = gt_model.resolve(intent, vault)            # raises ValueError on a refused effort
    if not res.get("model"):
        return None, None, "inherit (intent unmapped)"
    return res["model"], res.get("effort"), "intent %s (average profile)" % intent


def intent_settings(intent, vault=None, label=None):
    """-> (model alias or None, effort or None, source): an intent through the intent pack, as
    an Agent-tool alias, with no override and no setting consulted."""
    label = label or "intent %s" % intent
    if intent not in gt_model.INTENTS:
        raise ValueError("model_intent %r is not one of %s" % (intent, "|".join(gt_model.INTENTS)))
    res = gt_model.resolve(intent, vault)
    model = (res.get("model") or "").lower()
    alias = next((a for a in AGENT_MODELS if a in model), None)
    if not alias:
        return None, None, "%s, unmapped" % label
    effort = res.get("effort")
    if gt_model.effort_problem(alias, effort):
        effort = None                                   # never write a level Claude Code lowers
    return alias, effort, label


def tier_settings(tier, vault=None):
    """-> (model alias or None, effort or None, source): a tier through the intent pack, with
    no override and no setting consulted -- what a stage's shipped definition carries."""
    intent = gt_model.intent_for_tier(tier)
    return intent_settings(intent, vault, "task tier %s -> %s" % (tier, intent))


def module_agent_settings(key, intent, home=None, vault=None):
    """-> (model alias or None, effort or None, source) for a module plugin's agent (0.20.2),
    `key` its full name (gt-lotr:jira). None means the session's model (or effort)."""
    if _agent_setting() == "session":
        return None, None, "agent_models is session"
    o = model_choices(paths(home))["agents"].get(key)
    if isinstance(o, dict) and o.get("model") in AGENT_MODELS:
        effort = o.get("effort")
        if gt_model.effort_problem(o["model"], effort):
            effort = None
        return o["model"], effort, "agent override (%s)" % key
    return intent_settings(intent, vault, "agent intent %s" % intent)


def agent_settings(job, stage, tier, home=None, vault=None):
    """-> (model alias or None, effort or None, source) for a specialist agent. None means the
    session's model (or effort). Raises ValueError for a tier that is not one.

    A job-type override carries no effort: one definition file serves every kind of a stage,
    so such a job runs through the Agent tool's `model`, which has no effort parameter."""
    if _agent_setting() == "session":
        return None, None, "agent_models is session"
    choices = model_choices(paths(home))
    for key in (job, stage):
        o = choices["agents"].get(key) if key else None
        if isinstance(o, dict) and o.get("model") in AGENT_MODELS:
            effort = o.get("effort") if key == stage else None
            if gt_model.effort_problem(o["model"], effort):
                effort = None
            return o["model"], effort, "agent override (%s)" % key
    return tier_settings(tier, vault)


def agent_model(job, stage, tier, home=None, vault=None):
    """-> (model alias or None, source) for a specialist agent. None means the session's model.
    Raises ValueError for a tier that is not one."""
    model, _effort, source = agent_settings(job, stage, tier, home, vault)
    return model, source


def _stage_tiers(vault=None):
    """-> {stage: model_tier} from the effective stage specs (vault overrides applied)."""
    import gt_agent_spec                                  # noqa: E402
    specs, _ = gt_agent_spec.load_specs(vault)
    return {s: specs[s]["data"]["model_tier"] for s in gt_agent_spec.AGENT_STAGES if s in specs}


def _agent_setting():
    try:
        import gt_settings                                # noqa: E402
        return gt_settings.get("agent_models") or "task"
    except Exception:                                     # noqa: BLE001 - the default, never fail
        return "task"


def agent_rows(home=None, vault=None):
    """-> [{stage, tier, model, effort, source}] for every shipped agent stage, then every
    installed module agent (0.20.2; `stage` is its full name, `tier` its intent)."""
    rows = []
    for stage, tier in _stage_tiers(vault).items():
        model, effort, source = agent_settings(stage, stage, tier, home, vault)
        rows.append({"stage": stage, "tier": tier, "model": model, "effort": effort,
                     "source": source})
    seen = set()
    for _plugin, key, _path, intent in installed_module_agents(paths(home)):
        if key in seen:
            continue
        seen.add(key)
        try:
            model, effort, source = module_agent_settings(key, intent, home, vault)
        except ValueError as exc:
            model, effort, source = None, None, "REFUSED %s" % exc
        rows.append({"stage": key, "tier": intent, "model": model, "effort": effort,
                     "source": source})
    return rows


def agent_plan(P, vault, refused=None):
    """-> rows {plugin, skill, path, model, effort, source, agent} for each installed agent
    definition, from the stage's own resolution (a job-type override does not reach a file).
    A module agent the policy cannot resolve is left as shipped and named in `refused`."""
    tiers = _stage_tiers(vault)
    rows = []
    for plugin, stage, path in installed_agents(P):
        if stage not in tiers:
            continue
        model, effort, source = agent_settings(stage, stage, tiers[stage], P["home"], vault)
        rows.append({"plugin": plugin, "skill": "agent:%s" % stage, "path": str(path),
                     "model": model, "effort": effort, "source": source, "agent": True})
    for plugin, key, path, intent in installed_module_agents(P):
        try:
            model, effort, source = module_agent_settings(key, intent, P["home"], vault)
        except ValueError as exc:
            # Left as shipped -- so it runs on the session's model. Said, never skipped quietly.
            if refused is not None:
                refused.append("%s (%s): %s -- left as shipped, it runs on the session's model"
                               % (key, path, exc))
            continue
        rows.append({"plugin": plugin, "skill": "agent:%s" % key, "path": str(path),
                     "model": model, "effort": effort, "source": source, "agent": True})
    return rows


def rewrite(path, model, effort):
    """Set (or remove) model:/effort: in a definition's frontmatter (and drop a legacy
    writes_model: line). -> True when it changed."""
    # Bytes, not read_text (0.20.1): text mode turns CRLF into "\n" and the rewrite then
    # wrote the file back LF, so on Windows (a CRLF checkout) "inherit" did not restore the
    # bytes the install laid down. The file keeps the line ending it came with.
    text = Path(path).read_bytes().decode("utf-8")
    crlf = "\r\n" in text
    lines = text.replace("\r\n", "\n").split("\n")
    if not lines or lines[0].strip() != "---":
        return False
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return False
    head = [l for l in lines[1:end] if l.split(":", 1)[0].strip() not in FIELDS + LEGACY_KEYS]
    if model:
        head.append("model: %s" % model)
        if effort:
            head.append("effort: %s" % effort)
    new = "\n".join([lines[0]] + head + lines[end:])
    if crlf:
        new = new.replace("\n", "\r\n")
    if new == text:
        return False
    Path(path).write_bytes(new.encode("utf-8"))
    return True


def current_fields(path):
    """-> (model, effort) as the definition's frontmatter holds them."""
    lines = Path(path).read_text(encoding="utf-8").split("\n")
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), len(lines))
    got = {}
    for l in lines[1:end]:
        k, _, v = l.partition(":")
        if k.strip() in FIELDS:
            got[k.strip()] = v.strip()
    return got.get("model"), got.get("effort")


def current_tools(path):
    """-> the sorted list a definition's `tools:` frontmatter line names (empty when absent)."""
    lines = Path(path).read_text(encoding="utf-8").split("\n")
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), len(lines))
    for l in lines[1:end]:
        k, _, v = l.partition(":")
        if k.strip() == "tools":
            return sorted(t.strip() for t in v.split(",") if t.strip())
    return []


def tools_drift(P):
    """-> [str]: an installed module agent whose `tools:` differs from the shipped file's (the
    marketplace copy). A cached build from before a tool split (a reader that still lists
    call_write) is the case this exists for: the tool list is the security property, and an
    install can keep an older copy next to the new one."""
    out = []
    for plugin, key, path, _intent in installed_module_agents(P):
        shipped = P["market"] / plugin / "agents" / Path(path).name
        if not shipped.is_file() or Path(path).resolve() == shipped.resolve():
            continue
        try:
            have, want = current_tools(path), current_tools(shipped)
        except (OSError, UnicodeDecodeError):
            continue
        if have != want:
            out.append("%s (agent:%s): tools are %s, the shipped definition has %s -- an older "
                       "build is installed; reinstall gt-lotr" % (path, key, ",".join(have),
                                                                  ",".join(want)))
    return out


def writer_warnings(P, vault=None, home=None):
    """-> [str]: a module WRITER agent (name ends in `writer`) that resolves to haiku. A writer
    composes a payload exactly and refuses a mismatched spec; that is the job the balanced
    intent exists for, and the policy allows the override but says so."""
    out = []
    seen = set()
    for _plugin, key, path, intent in installed_module_agents(P):
        if key in seen or not (key.endswith(":writer") or key.endswith("-writer")):
            continue
        seen.add(key)
        try:
            model = module_agent_settings(key, intent, P["home"], vault)[0]
        except ValueError:
            continue
        if model == "haiku":
            out.append("%s runs on haiku (%s): a writer must follow an exact spec and refuse a "
                       "mismatched one, which is what the balanced intent (sonnet) is for"
                       % (key, path))
    return out


def plan(P, profile, vault):
    choices = model_choices(P)
    profile = profile or choices["profile"] or "inherit"
    rows, refused = [], []
    for plugin, skill, path in installed_skills(P):
        try:
            model, effort, source = resolve_one(plugin, skill, path, profile, choices, vault)
        except ValueError as exc:
            refused.append("%s/%s: %s" % (plugin, skill, exc))
            continue
        rows.append({"plugin": plugin, "skill": skill, "path": str(path), "model": model,
                     "effort": effort, "source": source})
    return profile, rows, refused


def cmd_apply(a):
    P = paths(a.home)
    if a.profile and a.profile not in PROFILES:
        return _bad_profile(a.profile)
    if getattr(a, "agents_only", False):
        # gt_settings runs this when agent_models changes: the agent definitions follow the
        # setting at once, and no skill file is touched (0.20.1).
        prev = _load(P["record"], {})
        prev = prev if isinstance(prev, dict) else {}
        profile, rows, refused = prev.get("profile"), [], []
        kept = {p: v for p, v in (prev.get("files") or {}).items() if not v.get("agent")}
    else:
        profile, rows, refused = plan(P, a.profile, a.vault)
        kept = {}
    try:
        agents = agent_plan(P, a.vault, refused)
    except ValueError as exc:
        agents = []
        refused.append("agent definitions: %s" % exc)
    changed = sum(rewrite(r["path"], r["model"], r["effort"]) for r in rows)
    achanged = sum(rewrite(r["path"], r["model"], r["effort"]) for r in agents)
    files = dict(kept)
    files.update({r["path"]: {"model": r["model"], "effort": r["effort"], "source": r["source"]}
                  for r in rows})
    files.update({r["path"]: {"model": r["model"], "effort": r["effort"],
                              "source": r["source"], "agent": True}
                  for r in agents})
    _atomic(P["record"], {"version": 1, "profile": profile,
                          "applied": time.strftime("%Y-%m-%dT%H:%M:%S%z"), "files": files})
    if getattr(a, "agents_only", False):
        print("model policy: %d installed agent definition(s), %d changed"
              % (len(agents), achanged))
    else:
        print("model policy: profile %s -- %d installed skill file(s), %d changed; "
              "%d agent definition(s), %d changed"
              % (profile, len(rows), changed, len(agents), achanged))
    for r in refused:
        print("  REFUSED %s" % r, file=sys.stderr)
    for w in writer_warnings(P, a.vault):
        print("  WARNING %s" % w, file=sys.stderr)
    return PROBLEM if refused else OK


def cmd_verify(a):
    P = paths(a.home)
    rec = _load(P["record"], None)
    tdrift = tools_drift(P)
    if not isinstance(rec, dict):
        for d in tdrift:
            print("  DRIFT " + d)
        for w in writer_warnings(P, a.vault):
            print("  WARNING " + w)
        if tdrift:
            print("model policy: %d agent definition(s) differ from the shipped tool list" % len(tdrift))
            return PROBLEM
        print("model policy: never applied on this machine -- nothing to verify")
        return OK
    drift = list(tdrift)
    recorded = rec.get("files") or {}
    for _plugin, skill, path in installed_skills(P) + [
            (p, "agent:%s" % s, f) for p, s, f in installed_agents(P)] + [
            (p, "agent:%s" % k, f) for p, k, f, _i in installed_module_agents(P)]:
        want = recorded.get(str(path))
        have = current_fields(path)
        if want is None:
            if any(have):
                drift.append("%s: model/effort %s present but not written by the policy"
                             % (path, have))
            continue
        for k, h in zip(FIELDS, have):
            if (want.get(k) or None) != (h or None):
                drift.append("%s (%s): %s is %r, the policy wrote %r"
                             % (path, skill, k, h, want.get(k)))
    # A module agent whose intent resolves to a model but whose file has none runs on the
    # session's model: name it whether or not the record has it (review m3, 2026-10-04).
    for _p, key, path, intent in installed_module_agents(P):
        try:
            model = module_agent_settings(key, intent, P["home"], a.vault)[0]
        except ValueError as exc:
            drift.append("%s (agent:%s): REFUSED %s -- it runs on the session's model"
                         % (path, key, exc))
            continue
        if model and not current_fields(path)[0]:
            line = "%s (agent:%s): no model, the policy resolves %s -- it runs on the session's " \
                   "model; run gt_model_policy.py apply" % (path, key, model)
            if not any(str(path) in d and "model is" in d for d in drift):
                drift.append(line)
    for d in drift:
        print("  DRIFT " + d)
    for w in writer_warnings(P, a.vault):
        print("  WARNING " + w)
    print("model policy: %s" % ("%d file(s) edited since the policy wrote them" % len(drift)
                                if drift else "every installed skill is as the policy wrote it"))
    return PROBLEM if drift else OK


def profile_table(profile, vault):
    if profile == "inherit":
        return [(i, None, None) for i in gt_model.INTENTS]
    if profile == "very-high":
        return [(i,) + VERY_HIGH for i in gt_model.INTENTS]
    out = []
    for i in gt_model.INTENTS:
        r = gt_model.resolve(i, vault)
        out.append((i, r.get("model"), r.get("effort")))
    return out


def cmd_table(a):
    profile = a.profile or model_choices(paths(a.home))["profile"] or "average"
    if profile not in PROFILES:
        return _bad_profile(profile)
    rows = profile_table(profile, a.vault)
    print("Model profile: %s" % profile)
    for intent, model, effort in rows:
        print("  %-9s %s" % (intent, "session model and effort" if not model
                             else "%s · %s" % (model, effort or "no effort setting")))
    if any(e in ("high", "xhigh", "max") for _i, _m, e in rows):
        print("  Note: efforts above medium use more of your Claude allowance.")
    return OK


def cmd_choose(a):
    if a.profile not in PROFILES:
        return _bad_profile(a.profile)
    P = paths(a.home)
    d = _load(P["choices"], {})
    d = d if isinstance(d, dict) else {}
    d.setdefault("version", 1)
    d.setdefault("choices", {})      # the module-choice shape every other reader expects
    d.setdefault("model", {})["profile"] = a.profile
    _atomic(P["choices"], d)
    print("model policy: profile %s recorded" % a.profile)
    return OK


def cmd_current(a):
    p = model_choices(paths(a.home))["profile"]
    if p:
        print(p)
    return OK


def _edit_override(a, value):
    P = paths(a.home)
    d = _load(P["choices"], {})
    d = d if isinstance(d, dict) else {}
    d.setdefault("version", 1)
    d.setdefault("choices", {})
    scope, key = (("skills", a.skill) if a.skill else ("agents", a.agent)
                  if getattr(a, "agent", None) else ("plugins", a.plugin))
    bucket = d.setdefault("model", {}).setdefault(scope, {})
    if value is None:
        bucket.pop(key, None)
    else:
        bucket[key] = value
    _atomic(P["choices"], d)
    # Re-applied at once: a choice that waits for the next install is a choice nobody sees.
    return cmd_apply(argparse.Namespace(home=a.home, vault=a.vault, profile=None))


def cmd_set(a):
    if not a.model:
        print("gt_model_policy: refused -- set needs --model", file=sys.stderr)
        return USAGE
    if a.agent:
        if a.model not in AGENT_MODELS:
            print("gt_model_policy: refused -- an agent's model is passed to the Agent tool, "
                  "which takes one of %s, got %r" % (", ".join(AGENT_MODELS), a.model),
                  file=sys.stderr)
            return USAGE
        v = {"model": a.model}
        if a.effort:
            import gt_agent_spec                          # noqa: E402
            # A module agent (plugin:name, 0.20.2) is one definition file, so it takes an
            # effort like a stage does.
            if a.agent not in gt_agent_spec.AGENT_STAGES and ":" not in a.agent:
                print("gt_model_policy: refused -- an effort override is per STAGE (%s): it is "
                      "written into that stage's agent definition, and one definition serves "
                      "every kind; %r is a job type, so it takes --model only"
                      % (", ".join(gt_agent_spec.AGENT_STAGES), a.agent), file=sys.stderr)
                return USAGE
            bad = gt_model.effort_problem(a.model, a.effort)
            if bad:
                print("gt_model_policy: refused -- %s" % bad, file=sys.stderr)
                return USAGE
            v["effort"] = a.effort
        return _edit_override(a, v)
    bad = gt_model.effort_problem(a.model, a.effort)
    if bad:
        print("gt_model_policy: refused -- %s" % bad, file=sys.stderr)
        return USAGE
    v = {"model": a.model}
    if a.effort:
        v["effort"] = a.effort
    return _edit_override(a, v)


def cmd_clear(a):
    return _edit_override(a, None)


def cmd_show(a):
    profile, rows, refused = plan(paths(a.home), None, a.vault)
    agents = agent_rows(a.home, a.vault)
    if a.json:
        print(json.dumps({"profile": profile, "skills": rows, "agents": agents,
                          "refused": refused}, indent=2))
        return PROBLEM if refused else OK
    print("Model profile: %s (skills)" % profile)
    for r in rows:
        print("  %-14s %-22s %-8s %-8s %s" % (r["plugin"], r["skill"], r["model"] or "session",
                                             r["effort"] or "-", r["source"]))
    print("Agents (by task; model and effort from each stage's agent definition):")
    for r in agents:
        print("  %-14s %-22s %-8s %-8s %s" % ("agent", r["stage"], r["model"] or "session",
                                             r["effort"] or "-", r["source"]))
    for r in refused:
        print("  REFUSED %s" % r)
    return PROBLEM if refused else OK


def _bad_profile(p):
    print("gt_model_policy: profile %r is not one of %s" % (p, ", ".join(PROFILES)),
          file=sys.stderr)
    return USAGE


def main(argv=None):
    ap = argparse.ArgumentParser(prog="gt_model_policy.py", description=__doc__.split("\n\n")[0])
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--home", help="the HOME whose install is changed (default: yours)")
    common.add_argument("--vault", help="vault whose local packs apply (Core rule 2: named)")
    sub = ap.add_subparsers(dest="cmd", required=True)
    for name, fn in (("apply", cmd_apply), ("table", cmd_table)):
        p = sub.add_parser(name, parents=[common])
        p.add_argument("--profile")
        if name == "apply":
            p.add_argument("--agents-only", action="store_true",
                           help="rewrite only the installed agent definitions (gt_settings "
                           "runs this when agent_models changes)")
        p.set_defaults(fn=fn)
    p = sub.add_parser("choose", parents=[common])
    p.add_argument("profile")
    p.set_defaults(fn=cmd_choose)
    for name, fn in (("current", cmd_current), ("verify", cmd_verify)):
        sub.add_parser(name, parents=[common]).set_defaults(fn=fn)
    for name, fn in (("set", cmd_set), ("clear", cmd_clear)):
        p = sub.add_parser(name, parents=[common])
        who = p.add_mutually_exclusive_group(required=True)
        who.add_argument("--skill")
        who.add_argument("--plugin")
        who.add_argument("--agent", help="a specialist agent: a stage (extract), a job type "
                         "(extract-docs) or a module agent (gt-lotr:jira); --effort not for a "
                         "job type")
        if name == "set":
            p.add_argument("--model")
            p.add_argument("--effort")
        p.set_defaults(fn=fn)
    p = sub.add_parser("show", parents=[common])
    p.add_argument("--json", action="store_true")
    p.set_defaults(fn=cmd_show)
    a = ap.parse_args(argv)
    return a.fn(a)


if __name__ == "__main__":
    sys.exit(main())
