#!/usr/bin/env python3
"""gt_pipeline.py -- a project's release pipeline: ordered, declared steps and gates, as data.

    gt_pipeline.py init   --repo R [--project SLUG] [--dry-run]     adopt it (never overwrites)
    gt_pipeline.py list   --repo R                                  the steps, in run order
    gt_pipeline.py check  --repo R                                  order, commands, release.sh current
    gt_pipeline.py add    <id> --repo R --cmd CMD [--kind step|gate] [--after ID]
                          [--guarantee TEXT] [--optional] [--dry-run]
    gt_pipeline.py set    <id> --repo R --cmd CMD [--dry-run]       change one step's command
    gt_pipeline.py remove <id> --repo R [--reason TEXT] [--dry-run] a default step needs --reason
    gt_pipeline.py render --repo R [--dry-run]                      regenerate release.sh
    gt_pipeline.py run    --repo R [--until ID] [--from ID] [--go] [--dry-run]
    gt_pipeline.py builtin <name> --repo R                          one default step (release.sh calls it)
    gt_pipeline.py flag   --vault V (--project SLUG --value yes|no|planned | --all-missing) [--dry-run]

WHY (owner, 2026-10-01): "If there is code in it that it default create the process flow
(release.sh) and then the user can add to it or define it more clearly as they proceed. And if
there are gates (copygt.sh for instance) it would be able to define those and put them into
order." Every miss in the gt 0.17.11 release was a step that lived only in someone's head. gt's
own dev/publish.sh shows the model that works -- steps as data, run in order, stop at the first
failure, no skip -- and this gives every project that model.

THE FILES, in the project's code root:

    release-pipeline.tsv   the steps, one TAB-separated row each: id, kind (step|gate), guarantee,
                           command, after (the id it must follow, or -), required (yes|no),
                           origin (default|user). Removals are kept as `# removed:` lines, with
                           the date and the reason -- a default gate never disappears silently.
    release.sh             GENERATED from the .tsv by gt_recipe.py (one tested template). Never
                           edited by hand; `check` fails while the two disagree. If the repo
                           already has a release.sh gt did not write, the generated script is
                           release-pipeline.sh instead, and nothing of the user's is touched.

THE DEFAULT STEPS (origin default), gt's own release gates:

    tests        @tests       the repo's suite, found as the commit guard finds it; records a receipt
    allin        @allin       /gt:gt-allin: scan, credentials, lint, validations
    branch       @branch      the work is on a branch, never the default branch
    install      @install     install + post-install validation, where the project installs something
    owner-gate   @owner-gate  STOPS for the owner's explicit go-ahead (release.sh --go)
    push         @push        git push of the current branch
    sync         @sync        downstream copy/sync -- not applicable until one is declared

A builtin exits 99 for "not applicable here" (printed SKIP-not-applicable). A gate that cannot
run is a FAIL, never a pass: `@install` in a repo that has an install.sh but no declared install
command FAILS and says how to declare it, rather than passing over the step that was forgotten in
0.17.11.

`/gt:gt-allin` runs `release.sh --until owner-gate` (with GT_PIPELINE_INSIDE=allin, so the
@tests and @allin steps report "covered" instead of running allin inside allin), and
`/gt:gt-allin-commit` refuses while a pre-commit step fails.

Exit: 0 ok | 1 a check/run failed | 2 usage or refused | 99 (builtin) not applicable
"""
import argparse
import datetime
import glob
import json
import os
import re
import shutil
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import gt_recipe                                            # noqa: E402

STEPS_FILE = "release-pipeline.tsv"
SCRIPT = "release.sh"
ALT_SCRIPT = "release-pipeline.sh"
SKIP = gt_recipe.SKIP_RC
VALUES = ("yes", "no", "planned")
GENERATED_MARK = "GENERATED by gt_recipe.py"

DEFAULT_STEPS = (
    ("tests", "step", "the test suite passed and a receipt was recorded", "@tests", "-", "yes"),
    ("allin", "gate", "every gt-allin check ran: scan, credentials, lint, validations",
     "@allin", "tests", "yes"),
    ("branch", "gate", "the work is on a branch, never the default branch", "@branch",
     "allin", "yes"),
    ("install", "step", "installed, and the post-install validation passed",
     "@install", "branch", "yes"),
    ("owner-gate", "gate", "the owner gave an explicit go-ahead", "@owner-gate",
     "install", "yes"),
    ("push", "step", "the branch is on the remote others read", "@push", "owner-gate", "yes"),
    ("sync", "step", "every downstream copy is updated", "@sync", "push", "yes"),
)
HEADER = (
    "# release pipeline -- the steps as DATA. release.sh is GENERATED from this file.\n"
    "# Columns, TAB-separated: id  kind(step|gate)  guarantee  command  after(-|id)  "
    "required(yes|no)  origin(default|user)\n"
    "# A command starting @ is a gt builtin; anything else runs from this directory.\n"
    "# Change it with gt_pipeline.py add / set / remove (they re-render release.sh), or edit it\n"
    "# and run gt_pipeline.py render. `gt_pipeline.py check` validates it.\n"
)


# --------------------------------------------------------------- the files ----

def repo_root(path):
    try:
        p = subprocess.run(["git", "-C", path, "rev-parse", "--show-toplevel"],
                           capture_output=True, text=True, timeout=10)
        if p.returncode == 0 and p.stdout.strip():
            return os.path.realpath(p.stdout.strip())
    except Exception:
        pass
    return os.path.realpath(path)


def steps_path(repo):
    return os.path.join(repo, STEPS_FILE)


def read_steps(repo):
    """-> (recipe dict, raw text). Raises OSError / RecipeError."""
    with open(steps_path(repo), encoding="utf-8") as fh:
        text = fh.read()
    return gt_recipe.parse_tsv(text), text


def script_name(recipe):
    return recipe["settings"].get("script") or SCRIPT


def script_path(repo, recipe):
    return os.path.join(repo, script_name(recipe))


def is_generated(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            return GENERATED_MARK in fh.read(4000)
    except OSError:
        return False


def serialise(recipe):
    lines = [HEADER.rstrip("\n")]
    for k in ("project", "script"):
        if recipe["settings"].get(k):
            lines.append("# %s: %s" % (k, recipe["settings"][k]))
    for s in recipe["steps"]:
        lines.append("\t".join(s[c] or "-" if c == "after" else s[c]
                               for c in gt_recipe.TSV_COLS))
    for rm in recipe["removed"]:
        lines.append("# removed: %s" % rm)
    return "\n".join(lines) + "\n"


def write_all(repo, recipe, dry_run=False):
    """Validate, write the .tsv and render release.sh from it. Refuses an invalid recipe."""
    text = serialise(recipe)
    recipe = gt_recipe.parse_tsv(text)                 # re-validate what will be written
    script = gt_recipe.render(recipe, text, STEPS_FILE)
    if dry_run:
        return text, script
    tmp = steps_path(repo) + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    os.replace(tmp, steps_path(repo))
    gt_recipe.write_script(script_path(repo, recipe), script)
    return text, script


def default_recipe(project=None, script=SCRIPT):
    r = gt_recipe._blank_recipe(script)
    if project:
        r["settings"]["project"] = project
    r["settings"]["script"] = script
    for sid, kind, g, cmd, after, req in DEFAULT_STEPS:
        r["steps"].append({"id": sid, "kind": kind, "guarantee": g, "command": cmd,
                           "after": after, "required": req, "origin": "default",
                           "body": [gt_recipe.command_line(cmd)]})
    return r


# ---------------------------------------------------------------- commands ----

def cmd_init(repo, project=None, dry_run=False):
    """Adopt the pipeline in a repo. Idempotent, and never overwrites anything."""
    sp = steps_path(repo)
    if os.path.exists(sp):
        try:
            recipe, text = read_steps(repo)
        except (OSError, gt_recipe.RecipeError) as exc:
            print("REFUSED: %s exists and is not a valid steps file (%s); nothing changed"
                  % (sp, exc))
            return 2
        target = script_path(repo, recipe)
        if os.path.exists(target):
            print("already adopted: %s and %s exist; nothing changed"
                  % (STEPS_FILE, script_name(recipe)))
            return 0
        print("%s %s from the existing %s" % ("would render" if dry_run else "rendered",
                                               script_name(recipe), STEPS_FILE))
        if not dry_run:
            gt_recipe.write_script(target, gt_recipe.render(recipe, text, STEPS_FILE))
        return 0
    script = SCRIPT
    if os.path.exists(os.path.join(repo, SCRIPT)) and not is_generated(os.path.join(repo, SCRIPT)):
        script = ALT_SCRIPT
        if os.path.exists(os.path.join(repo, ALT_SCRIPT)) and \
                not is_generated(os.path.join(repo, ALT_SCRIPT)):
            print("REFUSED: %s and %s both exist and gt wrote neither; nothing changed. Rename "
                  "one, then run init again." % (SCRIPT, ALT_SCRIPT))
            return 2
        print("note: this repo already has a %s gt did not write; it is left alone and the "
              "pipeline is generated as %s" % (SCRIPT, ALT_SCRIPT))
    recipe = default_recipe(project, script)
    write_all(repo, recipe, dry_run)
    print("%s %s and %s with the %d default step(s) in %s"
          % ("would write" if dry_run else "wrote", STEPS_FILE, script, len(DEFAULT_STEPS), repo))
    return 0


def cmd_list(repo):
    recipe, _ = read_steps(repo)
    print("release pipeline for %s (%s, generated from %s)"
          % (recipe["settings"].get("project") or os.path.basename(repo),
             script_name(recipe), STEPS_FILE))
    for n, s in enumerate(gt_recipe.order(recipe["steps"]), 1):
        print("%2d. %-12s %-5s %-8s required=%-3s %-40s %s"
              % (n, s["id"], s["kind"], s["origin"], s["required"], s["command"][:40],
                 s["guarantee"]))
    for rm in recipe["removed"]:
        print("    removed: %s" % rm)
    return 0


SHELL_WORDS = {"cd", "test", "[", "echo", "true", "false", "exit", "export", "printf", "set",
               ":", "source", ".", "eval", "exec", "command", "env", "bash", "sh", "python3"}


def command_exists(repo, cmd):
    """-> None if the step's command can be found, else why not."""
    cmd = cmd.strip()
    if cmd.startswith("@"):
        return None if cmd[1:] in gt_recipe.BUILTINS else "unknown builtin %s" % cmd
    toks = cmd.split()
    while toks and re.match(r"^[A-Za-z_][A-Za-z0-9_]*=", toks[0]):
        toks.pop(0)                                       # VAR=value prefixes
    if not toks:
        return "empty command"
    first = toks[0]
    if first in ("bash", "sh", "python3", "python") and len(toks) > 1 \
            and not toks[1].startswith("-"):
        target = toks[1]
        path = target if os.path.isabs(target) else os.path.join(repo, target)
        return None if os.path.isfile(os.path.expanduser(path)) else "%s does not exist" % target
    if first in SHELL_WORDS:
        return None
    if "/" in first:
        path = first if os.path.isabs(first) else os.path.join(repo, first)
        path = os.path.expanduser(path)
        if not os.path.isfile(path):
            return "%s does not exist" % first
        return None
    if shutil.which(first):
        return None
    return "%s is not a file in the repo or a command on PATH" % first


def check_problems(repo):
    """-> list of problems (empty = the pipeline is valid and release.sh is current)."""
    try:
        recipe, text = read_steps(repo)
    except OSError:
        return ["no %s in %s -- adopt it with: gt_pipeline.py init --repo %s"
                % (STEPS_FILE, repo, repo)]
    except gt_recipe.RecipeError as exc:
        return ["%s is invalid: %s" % (STEPS_FILE, exc)]
    out = []
    for s in recipe["steps"]:
        why = command_exists(repo, s["command"])
        if why:
            out.append("step %s: %s" % (s["id"], why))
    target = script_path(repo, recipe)
    try:
        with open(target, encoding="utf-8") as fh:
            have = fh.read()
    except OSError:
        out.append("%s is missing -- run: gt_pipeline.py render --repo %s"
                   % (script_name(recipe), repo))
    else:
        if have != gt_recipe.render(recipe, text, STEPS_FILE):
            out.append("%s is not what %s renders (hand-edited, or the steps changed without a "
                       "render) -- run: gt_pipeline.py render --repo %s"
                       % (script_name(recipe), STEPS_FILE, repo))
    return out


def cmd_check(repo):
    probs = check_problems(repo)
    if probs:
        for p in probs:
            print("FAIL  %s" % p)
        return 1
    recipe, _ = read_steps(repo)
    print("ok    %d step(s), in order: %s" % (len(recipe["steps"]), " -> ".join(
        s["id"] for s in gt_recipe.order(recipe["steps"]))))
    return 0


def cmd_add(repo, sid, cmd, kind="step", after=None, guarantee="", optional=False,
            dry_run=False):
    recipe, _ = read_steps(repo)
    if any(s["id"] == sid for s in recipe["steps"]):
        print("REFUSED: a step named %s already exists (use `set` to change its command)" % sid)
        return 2
    why = command_exists(repo, cmd)
    if why:
        print("REFUSED: %s -- a step whose command cannot be found would FAIL every run" % why)
        return 2
    ordered = gt_recipe.order(recipe["steps"])
    after = after or (ordered[-1]["id"] if ordered else "-")
    if after != "-" and not any(s["id"] == after for s in recipe["steps"]):
        print("REFUSED: --after %s names no step" % after)
        return 2
    new = {"id": sid, "kind": kind, "guarantee": guarantee or "%s passed" % sid,
           "command": cmd, "after": after, "required": "no" if optional else "yes",
           "origin": "user", "body": [gt_recipe.command_line(cmd)]}
    # Placed right after the step it follows, so the file reads in run order too.
    steps = recipe["steps"]
    pos = next((i + 1 for i, s in enumerate(steps) if s["id"] == after), len(steps))
    steps.insert(pos, new)
    try:
        write_all(repo, recipe, dry_run)
    except gt_recipe.RecipeError as exc:
        print("REFUSED: %s; nothing changed" % exc)
        return 2
    print("%s %s after %s" % ("would add" if dry_run else "added", sid, after))
    return cmd_list(repo) if not dry_run else 0


def cmd_set(repo, sid, cmd, dry_run=False):
    recipe, _ = read_steps(repo)
    step = next((s for s in recipe["steps"] if s["id"] == sid), None)
    if not step:
        print("REFUSED: no step named %s" % sid)
        return 2
    why = command_exists(repo, cmd)
    if why:
        print("REFUSED: %s" % why)
        return 2
    step["command"] = cmd
    step["body"] = [gt_recipe.command_line(cmd)]
    write_all(repo, recipe, dry_run)
    print("%s %s: %s" % ("would set" if dry_run else "set", sid, cmd))
    return 0


def cmd_remove(repo, sid, reason=None, dry_run=False):
    recipe, _ = read_steps(repo)
    step = next((s for s in recipe["steps"] if s["id"] == sid), None)
    if not step:
        print("REFUSED: no step named %s" % sid)
        return 2
    if step["origin"] == "default" and not (reason or "").strip():
        print("REFUSED: %s is a DEFAULT gate. Removing one needs --reason, which is recorded in "
              "%s -- each default exists because a release once went out without it." % (sid,
                                                                                 STEPS_FILE))
        return 2
    for s in recipe["steps"]:
        if s["after"] == sid:
            s["after"] = step["after"]                # keep the chain intact
    recipe["steps"] = [s for s in recipe["steps"] if s["id"] != sid]
    recipe["removed"].append("%s (%s) on %s: %s" % (sid, step["origin"],
                                                     datetime.date.today().isoformat(),
                                                     (reason or "no reason given").strip()))
    write_all(repo, recipe, dry_run)
    print("%s %s%s" % ("would remove" if dry_run else "removed", sid,
                       " (recorded: %s)" % reason if reason else ""))
    return 0


def cmd_render(repo, dry_run=False):
    recipe, text = read_steps(repo)
    script = gt_recipe.render(recipe, text, STEPS_FILE)
    target = script_path(repo, recipe)
    if os.path.exists(target) and not is_generated(target):
        print("REFUSED: %s exists and gt did not write it; nothing changed" % target)
        return 2
    if dry_run:
        print("would write %s (%d step(s))" % (target, len(recipe["steps"])))
        return 0
    gt_recipe.write_script(target, script)
    print("wrote %s from %s" % (target, STEPS_FILE))
    return 0


def cmd_run(repo, until=None, frm=None, go=False, dry_run=False, inside=None):
    probs = check_problems(repo)
    if probs:
        for p in probs:
            print("FAIL  %s" % p)
        print("the pipeline is not runnable until `gt_pipeline.py check` passes")
        return 1
    recipe, _ = read_steps(repo)
    cmd = ["bash", script_path(repo, recipe)]
    if until:
        cmd += ["--until", until]
    if frm:
        cmd += ["--from", frm]
    if go:
        cmd.append("--go")
    if dry_run:
        cmd.append("--dry-run")
    env = dict(os.environ)
    if inside:
        env["GT_PIPELINE_INSIDE"] = inside
    env.setdefault("GT_PIPELINE_PY", os.path.abspath(__file__))
    env.setdefault("GT_METRICS_PY", os.path.join(HERE, "gt_metrics.py"))
    sys.stdout.flush()
    started = time.time()
    proc = subprocess.Popen(cmd, cwd=repo, env=env, stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, text=True)
    failed = None
    for line in proc.stdout:                     # streamed, so a long step stays visible
        sys.stdout.write(line)
        sys.stdout.flush()
        m = re.match(r"^STOPPED at the first failure: (\S+)", line)
        if m:
            failed = m.group(1)
    rc = proc.wait()
    if not dry_run:
        record_run(repo, rc, until, failed, started)
    return rc


LAST_RUNS = os.path.expanduser("~/.claude/golden-thread/pipeline-last.json")


def record_run(repo, rc, until, failed, started):
    """The newest outcome per repo, which /gt:gt-allin-commit reads: a failed pre-commit step
    refuses the commit, and --allow-findings cannot wave it through."""
    try:
        with open(LAST_RUNS) as fh:
            data = json.load(fh)
    except Exception:
        data = {}
    data[repo] = {"rc": rc, "until": until or "", "failed": failed or "",
                  "started": started, "finished": time.time()}
    try:
        os.makedirs(os.path.dirname(LAST_RUNS), exist_ok=True)
        tmp = LAST_RUNS + ".tmp"
        with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
            json.dump(data, fh, indent=1)
        os.replace(tmp, LAST_RUNS)
    except OSError:
        pass


def last_run(repo):
    try:
        with open(LAST_RUNS) as fh:
            return json.load(fh).get(repo)
    except Exception:
        return None


# ---------------------------------------------------------------- builtins ----

def _git(repo, *args):
    try:
        p = subprocess.run(["git", "-C", repo, *args], capture_output=True, text=True, timeout=30)
        return p.returncode, (p.stdout or "").strip()
    except Exception as exc:
        return 1, str(exc)


def default_branch(repo):
    rc, out = _git(repo, "symbolic-ref", "--quiet", "refs/remotes/origin/HEAD")
    if rc == 0 and out:
        return out.rsplit("/", 1)[-1]
    for cand in ("main", "master"):
        if _git(repo, "rev-parse", "--verify", "--quiet", "refs/heads/" + cand)[0] == 0:
            return cand
    return "main"


def current_branch(repo):
    rc, out = _git(repo, "symbolic-ref", "--quiet", "--short", "HEAD")
    return out if rc == 0 else ""


def _vault():
    v = os.environ.get("GT_VAULT")
    if v:
        return v
    try:
        with open(os.path.expanduser("~/.claude/vault-config.json")) as fh:
            return json.load(fh).get("vault_path")
    except Exception:
        return None


def builtin(name, repo):
    inside = os.environ.get("GT_PIPELINE_INSIDE", "")
    py = sys.executable or "python3"
    if name == "tests":
        if inside == "allin":
            print("  covered: /gt:gt-allin runs the suite as its `tests` member in this same run")
            return 0
        if os.path.exists(os.path.join(repo, ".gt-no-test-gate")):
            print("  this repo is exempt from the test gate (.gt-no-test-gate)")
            return SKIP
        rc = subprocess.run([py, os.path.join(HERE, "gt_test_receipt.py"), "run",
                             "--repo", repo]).returncode
        if rc == 3:
            print("  FAIL: no test entry point was found, and a step that cannot run is not a "
                  "pass. Add one (tests/run.sh, pytest.ini, package.json test, ...), or exempt "
                  "the repo with .gt-no-test-gate")
            return 1
        return rc
    if name == "allin":
        if inside == "allin":
            print("  covered: this run is inside /gt:gt-allin, whose members are these checks")
            return 0
        vault = _vault()
        cmd = [py, os.path.join(HERE, "gt_allin.py"), "--repo", repo,
               "--only", "scan,secrets,validations" + (",lint" if vault else "")]
        if vault:
            cmd += ["--vault", vault]
        env = dict(os.environ, GT_PIPELINE_INSIDE="pipeline")
        return subprocess.run(cmd, env=env).returncode
    if name == "branch":
        cur = current_branch(repo)
        if not cur:
            print("  FAIL: HEAD is detached -- release from a named branch")
            return 1
        dflt = default_branch(repo)
        if cur == dflt:
            print("  FAIL: on the default branch (%s). Work goes on a branch, never the default "
                  "branch." % cur)
            return 1
        print("  on branch %s (default: %s)" % (cur, dflt))
        return 0
    if name == "install":
        if os.path.exists(os.path.join(repo, "install.sh")):
            print("  FAIL: this project installs something (install.sh), and no install + "
                  "post-install validation command is declared. A gate that cannot run is not a "
                  "pass -- in gt 0.17.11 post-install validation was added only when asked.\n"
                  "  Declare it: gt_pipeline.py set install --repo %s --cmd '<install and "
                  "validate>'" % repo)
            return 1
        print("  nothing to install (no install.sh)")
        return SKIP
    if name == "owner-gate":
        if os.environ.get("GT_OWNER_GO", "").lower() == "yes":
            print("  go-ahead given (--go)")
            return 0
        print("  STOP: waiting for the owner's explicit go-ahead. When the owner says go, "
              "run release.sh --from owner-gate --go")
        return 1
    if name == "push":
        rc, remotes = _git(repo, "remote")
        if rc != 0 or not remotes.strip():
            print("  no git remote: nothing to push to")
            return SKIP
        cur = current_branch(repo)
        if not cur:
            print("  FAIL: HEAD is detached")
            return 1
        rc, up = _git(repo, "rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{u}")
        cmd = ["git", "-C", repo, "push"] + ([] if rc == 0 and up else
                                             ["-u", remotes.split()[0], cur])
        return subprocess.run(cmd).returncode
    if name == "sync":
        print("  no downstream copy declared. Add one where it belongs, e.g.\n"
              "    gt_pipeline.py add copy --repo %s --kind gate --cmd '<copy command>' "
              "--after sync" % repo)
        return SKIP
    print("unknown builtin %s" % name)
    return 2


# ------------------------------------------------------------ vault flag ----

def _readme(vault, slug):
    return os.path.join(vault, "Projects", slug, "README.md")


def _frontmatter(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            text = fh.read()
    except OSError:
        return None
    m = re.match(r"^---\s*\n(.*?)\n---", text, re.S)
    if not m:
        return None
    return dict(re.findall(r"^([a-z_]+):\s*(.*)$", m.group(1), re.M))


def projects_missing_flag(vault):
    out = []
    base = os.path.join(vault, "Projects")
    for readme in sorted(glob.glob(os.path.join(base, "*", "README.md")) +
                         glob.glob(os.path.join(base, "*", "*", "README.md"))):
        proj = os.path.dirname(readme)
        if not os.path.exists(os.path.join(proj, "idea.md")):
            continue
        fm = _frontmatter(readme)
        if fm is None or "release_pipeline" in fm:
            continue
        out.append(os.path.relpath(proj, base).replace(os.sep, "/"))
    return out


def queue_flag(vault, rel_project, value, dry_run=False):
    cmd = [sys.executable or "python3", os.path.join(HERE, "gt_write_queue.py"),
           "--vault", vault, "--path", "Projects/%s/README.md" % rel_project,
           "--op", "set-property", "--key", "release_pipeline", "--value", value,
           "--hint", "gt_pipeline: release_pipeline flag"]
    if dry_run:
        cmd.append("--dry-run")
    p = subprocess.run(cmd, capture_output=True, text=True)
    return p.returncode, (p.stdout + p.stderr).strip()


def cmd_flag(vault, project=None, value=None, all_missing=False, dry_run=False, drain=True):
    vault = os.path.abspath(os.path.expanduser(vault))
    if all_missing:
        todo = [(p, "planned") for p in projects_missing_flag(vault)]
    else:
        if value not in VALUES:
            print("REFUSED: --value must be one of %s" % ", ".join(VALUES))
            return 2
        if not os.path.isfile(_readme(vault, project)):
            print("REFUSED: no project README at Projects/%s/README.md" % project)
            return 2
        todo = [(project, value)]
    bad = 0
    for rel, val in todo:
        rc, out = queue_flag(vault, rel, val, dry_run)
        print("%s release_pipeline: %s  Projects/%s/README.md%s"
              % ("would queue" if dry_run else ("queued" if rc == 0 else "REFUSED"), val, rel,
                 "" if rc == 0 else "  (%s)" % out[-200:]))
        bad += rc != 0
    if not todo:
        print("every project README already carries release_pipeline")
    if todo and drain and not dry_run:
        p = subprocess.run([sys.executable or "python3", os.path.join(HERE, "gt_broker.py"),
                            "drain", "--vault", vault], capture_output=True, text=True)
        print((p.stdout or p.stderr).strip().splitlines()[-1:] and
              (p.stdout or p.stderr).strip().splitlines()[-1] or "drained")
    return 1 if bad else 0


# --------------------------------------------------------------------- CLI ----

def main(argv=None):
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--repo", default=".", help="the project's code root (default: here)")
    common.add_argument("--dry-run", action="store_true", default=argparse.SUPPRESS,
                        help="say what would change; write nothing")
    common.add_argument("--vault", default=argparse.SUPPRESS,
                        help="the vault (only `flag` writes one)")
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0], parents=[common])
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("init", parents=[common], help="adopt the pipeline (never overwrites)")
    p.add_argument("--project", help="the vault project slug, recorded in the steps file")
    sub.add_parser("list", parents=[common], help="the steps in run order")
    sub.add_parser("check", parents=[common], help="validate order, commands, release.sh")
    p = sub.add_parser("add", parents=[common], help="insert a step or gate")
    p.add_argument("id")
    p.add_argument("--cmd", dest="cmdline", required=True)
    p.add_argument("--kind", choices=("step", "gate"), default="step")
    p.add_argument("--after", help="the step it must follow (default: the last step)")
    p.add_argument("--guarantee", default="", help="one line: what passing it guarantees")
    p.add_argument("--optional", action="store_true", help="a failure is reported, not fatal")
    p = sub.add_parser("set", parents=[common], help="change one step's command")
    p.add_argument("id")
    p.add_argument("--cmd", dest="cmdline", required=True)
    p = sub.add_parser("remove", parents=[common], help="remove a step (a default needs --reason)")
    p.add_argument("id")
    p.add_argument("--reason")
    sub.add_parser("render", parents=[common], help="regenerate release.sh from the steps file")
    p = sub.add_parser("run", parents=[common], help="run release.sh")
    p.add_argument("--until")
    p.add_argument("--from", dest="frm")
    p.add_argument("--go", action="store_true", help="the owner's explicit go-ahead")
    p.add_argument("--inside", choices=("allin",), help=argparse.SUPPRESS)
    p = sub.add_parser("builtin", parents=[common], help="run one default step")
    p.add_argument("name", choices=gt_recipe.BUILTINS)
    p = sub.add_parser("flag", parents=[common],
                       help="set release_pipeline on a project README (through the write queue)")
    p.add_argument("--project")
    p.add_argument("--value", choices=VALUES)
    p.add_argument("--all-missing", action="store_true",
                   help="record `planned` on every project README without the flag")
    a = ap.parse_args(argv)
    dry = getattr(a, "dry_run", False)

    if a.cmd == "flag":
        vault = getattr(a, "vault", None)
        if not vault:
            print("REFUSED: flag writes the vault, so --vault is required (never inferred)")
            return 2
        if not a.all_missing and not (a.project and a.value):
            print("REFUSED: give --project and --value, or --all-missing")
            return 2
        return cmd_flag(vault, a.project, a.value, a.all_missing, dry)

    repo = repo_root(os.path.abspath(os.path.expanduser(a.repo)))
    if a.cmd == "builtin":
        return builtin(a.name, repo)
    if a.cmd == "init":
        return cmd_init(repo, a.project, dry)
    if a.cmd == "check":
        return cmd_check(repo)
    try:
        if a.cmd == "list":
            return cmd_list(repo)
        if a.cmd == "add":
            return cmd_add(repo, a.id, a.cmdline, a.kind, a.after, a.guarantee, a.optional, dry)
        if a.cmd == "set":
            return cmd_set(repo, a.id, a.cmdline, dry)
        if a.cmd == "remove":
            return cmd_remove(repo, a.id, a.reason, dry)
        if a.cmd == "render":
            return cmd_render(repo, dry)
        if a.cmd == "run":
            return cmd_run(repo, a.until, a.frm, a.go, dry, a.inside)
    except OSError:
        print("no %s in %s -- adopt it with: gt_pipeline.py init --repo %s"
              % (STEPS_FILE, repo, repo))
        return 2
    except gt_recipe.RecipeError as exc:
        print("%s is invalid: %s" % (STEPS_FILE, exc))
        return 2
    return 2


if __name__ == "__main__":
    sys.exit(main())
