#!/usr/bin/env python3
"""Per-session spool files, and the deterministic merge that renders them.

## Why this exists

`log.md` and `decisions.md` are append-only, shared, and live in ONE working tree.
There are no branches to collide and no merge to resolve -- just last-writer-wins,
invisible at the moment it happens. On 2026-09-10 a session appended one line to
`log.md` and committed it, carrying NINE lines written by earlier sessions that
happened to be uncommitted in the shared tree. Nothing was lost, but "commit only
your own files" is unenforceable while everyone's work is in one file.

Claims do not help here. `gt_session.py` claims are advisory by design -- in one
working tree a stuck lock is worse than the corruption it prevents -- and
`guard_session_claims` inspects `Write`/`Edit` while `log.md` is appended with `>>`
and `tee`, which it deliberately does not see. The protection that exists does not
cover the file that needs it most.

So this removes the shared write target instead of arbitrating access to it. Every
session appends to a file only it writes; the shared file is RENDERED from them, the
way `TASKS.md` is already rendered rather than edited.

## The baseline is what makes adoption safe

Migration copies the existing `log.md` (or `decisions.md`) into `0000-baseline.md`,
which sorts first and is never written again. No history is rewritten, no past
session has to be reconstructed, and nothing is renumbered. The gate on migration is
a BYTE-IDENTICAL round trip: if the merge cannot reproduce the original file exactly,
the design is wrong and nothing is committed.

## Ordering is total and machine-independent

Two machines merging the same spools must produce byte-identical output, or the
GENERATED file starts conflicting in git -- worse than the problem being solved. So
the sort key uses nothing that varies by machine: no mtimes, no directory order, no
locale. Baseline first, then (timestamp, session-id, index-within-that-session).
Minute-resolution timestamps collide often, so the session id is doing real work as
the second key, and the index preserves a session's own order.
"""
import os
import re
import sys
from pathlib import Path

BASELINE = "0000-baseline.md"
BANNER = ("<!-- GENERATED by gt_log.py / gt_adr.py from Projects/golden-thread/spool/. "
          "Do not hand-edit: your change is lost at the next merge. "
          "Add entries with the tool; run `merge` to regenerate. -->")

# A leading `YYYY-MM-DD` with an optional `HH:MM` and zone. Kept deliberately loose:
# the sort must not depend on a session having written the optional parts, and a line
# that carries no date at all still has to sort somewhere stable rather than crash.
STAMP = re.compile(r"^(\d{4}-\d{2}-\d{2})(?:\s+(\d{2}:\d{2}))?")

# Owner files are not guaranteed UTF-8 (a latin-1 `\xe9` in a years-old log.md is real).
# Until 0.15.0 they were read with errors="replace", which wrote U+FFFD into the baseline
# and the generated file -- and the round-trip gate compared two already-replaced copies,
# so it passed. surrogateescape maps every undecodable byte to a lone surrogate and back,
# so read -> render -> write is byte-identical for ANY input, and str equality means byte
# equality. Every read that can flow into a write, and every such write, uses it.
OWNER_ERRORS = "surrogateescape"


def read_owner(path):
    """Text of an owner file whose bytes must survive a round trip unchanged."""
    return Path(path).read_text(encoding="utf-8", errors=OWNER_ERRORS)


def owner_bytes(text):
    """Bytes of `text` read with read_owner -- the inverse, undecodable bytes restored."""
    return text.encode("utf-8", OWNER_ERRORS)


def session_id(explicit=None):
    """The current session id, resolved exactly as gt_session.py resolves it.

    Reused rather than reinvented so a spool file and a session claim name the same
    session -- `gt_session.py list` can then say whether the owner of an unfinished
    allocation is still alive.
    """
    if explicit:
        return explicit
    for var in ("CLAUDE_CODE_SESSION_ID", "CLAUDE_SESSION_ID", "GT_SESSION_ID"):
        v = os.environ.get(var)
        if v:
            return re.sub(r"[^A-Za-z0-9._-]", "-", v)[:80]
    return "unknown-%d" % os.getpid()


def vault_root(explicit=None):
    """Resolve the vault: --vault, then $GT_VAULT, then ~/.claude/vault-config.json."""
    if explicit:
        return Path(explicit).expanduser().resolve()
    if os.environ.get("GT_VAULT"):
        return Path(os.environ["GT_VAULT"]).expanduser().resolve()
    import json
    cfg = Path.home() / ".claude" / "vault-config.json"
    try:
        p = json.loads(cfg.read_text(encoding="utf-8")).get("vault_path")
    except Exception:
        p = None
    if not p:
        raise SystemExit("no vault: pass --vault, set GT_VAULT, or run /gt:gt-init")
    return Path(p).expanduser().resolve()


def spool_dir(vault, kind, project=None):
    """`<vault>/Projects/golden-thread/spool/<kind>[/<project>]`."""
    d = Path(vault) / "Projects" / "golden-thread" / "spool" / kind
    if project:
        d = d / project
    return d


def _safe_write(target, text):
    """Write through safe_write.py when it is beside us, else atomically.

    safe_write refuses rather than replacing a file it cannot read, which is the
    behaviour worth having on a session's own spool; but these tools must also work
    in a vault whose tools predate it, so the fallback is a plain atomic replace.
    """
    target = Path(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    sw = Path(__file__).resolve().parent / "safe_write.py"
    if sw.is_file():
        try:
            import importlib.util
            spec = importlib.util.spec_from_file_location("_sw", str(sw))
            m = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(m)
            m.write(str(target), text, "a" if target.exists() else "w")
            return
        except Exception:
            pass
    with open(target, "a", encoding="utf-8") as fh:
        fh.write(text)


def append(vault, kind, text, project=None, sid=None):
    """Append one entry to THIS session's spool file. Never touches a shared file."""
    sid = session_id(sid)
    d = spool_dir(vault, kind, project)
    d.mkdir(parents=True, exist_ok=True)
    if not text.endswith("\n"):
        text += "\n"
    p = d / ("%s.md" % sid)
    _safe_write(p, text)
    return p


def roundtrip_note(produced_body, original):
    """Is the rendered body faithful to the original? -> "" identical, str note, None no.

    The migration gate claims a byte-identical round trip. Until 0.12.0 both sides
    were compared with `rstrip("\\n")`, so a file ending in a blank line passed the
    gate and was then written WITHOUT that line: on 2026-09-11 migrating 42 projects
    silently dropped one from `homekit-bridge/decisions.md`. A gate that normalises
    the thing it is checking is not a gate.

    Trailing blank lines are still not worth refusing a migration over -- so the
    difference is ANNOUNCED and the caller prints it, rather than tolerated in
    silence. Any other difference still refuses.
    """
    if produced_body == original:
        return ""
    if produced_body.rstrip("\n") != original.rstrip("\n"):
        return None
    lost = len(original) - len(original.rstrip("\n"))
    kept = len(produced_body) - len(produced_body.rstrip("\n"))
    delta = lost - kept
    if delta > 0:
        return " (dropped %d trailing blank line(s) the original ended with)" % delta
    return " (added %d trailing blank line(s))" % -delta


def _sort_key(fname, index, line):
    """Baseline first, then (timestamp, session id, index within that file).

    Every component is stable across machines. `index` keeps a single session's own
    entries in the order it wrote them even when their timestamps are identical,
    which at minute resolution is the common case rather than the rare one.
    """
    if fname == BASELINE:
        return (0, "", "", index)
    m = STAMP.match(line)
    stamp = (m.group(1) + " " + (m.group(2) or "")) if m else ""
    return (1, stamp, fname, index)


def lines(vault, kind, project=None):
    """Every spooled line, in merge order. Blank lines are preserved inside a file."""
    d = spool_dir(vault, kind, project)
    if not d.is_dir():
        return []
    out = []
    for f in sorted(d.iterdir()):
        if not f.is_file() or f.suffix != ".md":
            continue
        try:
            body = read_owner(f)
        except OSError:
            continue
        for i, ln in enumerate(body.splitlines()):
            out.append((_sort_key(f.name, i, ln), ln))
    out.sort(key=lambda t: t[0])
    return [ln for _, ln in out]


def write_if_changed(target, text):
    """Replace `target` only when the bytes differ.

    Idempotence is an acceptance criterion, not a nicety: a merge that rewrites an
    unchanged file makes every session's `git status` dirty and re-teaches people to
    ignore it.
    """
    target = Path(target)
    new = owner_bytes(text)
    try:
        if target.read_bytes() == new:
            return False
    except OSError:
        pass
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(target.suffix + ".gt-tmp")
    with open(tmp, "wb") as fh:
        fh.write(new)
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, target)
    return True


def hand_written(target, rendered):
    """Lines in the generated `target` that `rendered` does not produce -> [str].

    The banner says "do not hand-edit", but people do, and until 0.15.0 the next render
    (any `gt_log.py add`, including the receipt install.sh writes) deleted those lines
    with no word. A line counts when the current file has it and a render of the spool
    does not: it was typed into the file, or a generated line was changed by hand. Blank
    lines and the banner are ignored; a file that is not generated returns nothing (the
    callers refuse those before rendering)."""
    import difflib
    target = Path(target)
    if not target.is_file() or not is_generated(target):
        return []
    current = read_owner(target)
    if current == rendered:
        return []
    cur, new = current.splitlines(), rendered.splitlines()
    out = []
    for op, i1, i2, _j1, _j2 in difflib.SequenceMatcher(None, cur, new,
                                                        autojunk=False).get_opcodes():
        if op in ("delete", "replace"):
            out.extend(l for l in cur[i1:i2] if l.strip() and "GENERATED by" not in l)
    return out


def capture_hand_written(vault, kind, found, project=None):
    """Keep hand-written lines by spooling them -> the spool file written.

    They go into `hand-edits-<UTC time>.md` in the same spool, verbatim and in their
    order, so every later render carries them. Where a line lands follows the merge
    order like any spooled line: a line starting with a date sorts by that date (a log
    entry lands where it was); a line with no date sorts straight after the baseline."""
    import time
    d = spool_dir(vault, kind, project)
    d.mkdir(parents=True, exist_ok=True)
    p = d / ("hand-edits-%s.md" % time.strftime("%Y%m%dT%H%M%SZ", time.gmtime()))
    with open(p, "ab") as fh:
        fh.write(owner_bytes("".join(l + "\n" for l in found)))
    return p


def is_generated(path):
    """True when `path` carries the generated banner."""
    try:
        return BANNER.split("GENERATED")[0] + "GENERATED" in Path(path).read_text(
            encoding="utf-8", errors="replace")[:600]
    except OSError:
        return False
